// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataSourceSpec defines the desired state of DataSource.
//
// The structure of a data source.
type DataSourceSpec struct {

	// The Amazon Web Services account ID.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// The credentials Amazon Quick Sight that uses to connect to your underlying
	// source. Currently, only credentials based on user name and password are supported.
	Credentials *DataSourceCredentials `json:"credentials,omitempty"`
	// When you create the data source, Amazon Quick Sight adds the data source
	// to these folders.
	FolderARNs []*string `json:"folderARNs,omitempty"`
	// An ID for the data source. This ID is unique per Amazon Web Services Region
	// for each Amazon Web Services account.
	// +kubebuilder:validation:Required
	ID *string `json:"id"`
	// A display name for the data source.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The parameters that Amazon Quick Sight uses to connect to your underlying
	// source.
	Parameters *DataSourceParameters `json:"parameters,omitempty"`
	// A list of resource permissions on the data source.
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
	// Secure Socket Layer (SSL) properties that apply when Amazon Quick Sight connects
	// to your underlying source.
	SSLProperties *SSLProperties `json:"sslProperties,omitempty"`
	// Contains a map of the key-value pairs for the resource tag or tags assigned
	// to the data source.
	Tags []*Tag `json:"tags,omitempty"`
	// The type of the data source. To return a list of all data sources, use ListDataSources.
	//
	// Use AMAZON_ELASTICSEARCH for Amazon OpenSearch Service.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Type *string `json:"type,omitempty"`
	// Use this parameter only when you want Amazon Quick Sight to use a VPC connection
	// when connecting to your underlying source.
	VPCConnectionProperties *VPCConnectionProperties `json:"vpcConnectionProperties,omitempty"`
}

// DataSourceStatus defines the observed state of DataSource
type DataSourceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time that this data source was created.
	// +kubebuilder:validation:Optional
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	// Error information from the last update or the creation of the data source.
	// +kubebuilder:validation:Optional
	ErrorInfo *DataSourceErrorInfo `json:"errorInfo,omitempty"`
	// The last time that this data source was updated.
	// +kubebuilder:validation:Optional
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	// The status of the data source. Possible values are CREATION_IN_PROGRESS,
	// CREATION_SUCCESSFUL, CREATION_FAILED, UPDATE_IN_PROGRESS, UPDATE_SUCCESSFUL,
	// UPDATE_FAILED, or DELETED. The resource is considered synced when the status
	// is CREATION_SUCCESSFUL or UPDATE_SUCCESSFUL.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// DataSource is the Schema for the DataSources API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DataSource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DataSourceSpec   `json:"spec,omitempty"`
	Status            DataSourceStatus `json:"status,omitempty"`
}

// DataSourceList contains a list of DataSource
// +kubebuilder:object:root=true
type DataSourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataSource `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataSource{}, &DataSourceList{})
}
