// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionConnectorErrorType string

const (
	ActionConnectorErrorType_INTERNAL_FAILURE ActionConnectorErrorType = "INTERNAL_FAILURE"
)

type ActionConnectorSearchFilterNameEnum string

const (
	ActionConnectorSearchFilterNameEnum_ACTION_CONNECTOR_NAME             ActionConnectorSearchFilterNameEnum = "ACTION_CONNECTOR_NAME"
	ActionConnectorSearchFilterNameEnum_ACTION_CONNECTOR_TYPE             ActionConnectorSearchFilterNameEnum = "ACTION_CONNECTOR_TYPE"
	ActionConnectorSearchFilterNameEnum_DIRECT_QUICKSIGHT_OWNER           ActionConnectorSearchFilterNameEnum = "DIRECT_QUICKSIGHT_OWNER"
	ActionConnectorSearchFilterNameEnum_DIRECT_QUICKSIGHT_SOLE_OWNER      ActionConnectorSearchFilterNameEnum = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	ActionConnectorSearchFilterNameEnum_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER ActionConnectorSearchFilterNameEnum = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	ActionConnectorSearchFilterNameEnum_QUICKSIGHT_OWNER                  ActionConnectorSearchFilterNameEnum = "QUICKSIGHT_OWNER"
	ActionConnectorSearchFilterNameEnum_QUICKSIGHT_VIEWER_OR_OWNER        ActionConnectorSearchFilterNameEnum = "QUICKSIGHT_VIEWER_OR_OWNER"
)

type ActionConnectorType string

const (
	ActionConnectorType_AMAZON_BEDROCK_AGENT_RUNTIME           ActionConnectorType = "AMAZON_BEDROCK_AGENT_RUNTIME"
	ActionConnectorType_AMAZON_BEDROCK_DATA_AUTOMATION_RUNTIME ActionConnectorType = "AMAZON_BEDROCK_DATA_AUTOMATION_RUNTIME"
	ActionConnectorType_AMAZON_BEDROCK_RUNTIME                 ActionConnectorType = "AMAZON_BEDROCK_RUNTIME"
	ActionConnectorType_AMAZON_COMPREHEND                      ActionConnectorType = "AMAZON_COMPREHEND"
	ActionConnectorType_AMAZON_COMPREHEND_MEDICAL              ActionConnectorType = "AMAZON_COMPREHEND_MEDICAL"
	ActionConnectorType_AMAZON_S3                              ActionConnectorType = "AMAZON_S3"
	ActionConnectorType_AMAZON_TEXTRACT                        ActionConnectorType = "AMAZON_TEXTRACT"
	ActionConnectorType_ASANA                                  ActionConnectorType = "ASANA"
	ActionConnectorType_ATLASSIAN_CONFLUENCE                   ActionConnectorType = "ATLASSIAN_CONFLUENCE"
	ActionConnectorType_BAMBOO_HR                              ActionConnectorType = "BAMBOO_HR"
	ActionConnectorType_GENERIC_HTTP                           ActionConnectorType = "GENERIC_HTTP"
	ActionConnectorType_JIRA_CLOUD                             ActionConnectorType = "JIRA_CLOUD"
	ActionConnectorType_MICROSOFT_ONEDRIVE                     ActionConnectorType = "MICROSOFT_ONEDRIVE"
	ActionConnectorType_MICROSOFT_OUTLOOK                      ActionConnectorType = "MICROSOFT_OUTLOOK"
	ActionConnectorType_MICROSOFT_SHAREPOINT                   ActionConnectorType = "MICROSOFT_SHAREPOINT"
	ActionConnectorType_MICROSOFT_TEAMS                        ActionConnectorType = "MICROSOFT_TEAMS"
	ActionConnectorType_PAGERDUTY_ADVANCE                      ActionConnectorType = "PAGERDUTY_ADVANCE"
	ActionConnectorType_SALESFORCE_CRM                         ActionConnectorType = "SALESFORCE_CRM"
	ActionConnectorType_SAP_BILLOFMATERIALS                    ActionConnectorType = "SAP_BILLOFMATERIALS"
	ActionConnectorType_SAP_BUSINESSPARTNER                    ActionConnectorType = "SAP_BUSINESSPARTNER"
	ActionConnectorType_SAP_MATERIALSTOCK                      ActionConnectorType = "SAP_MATERIALSTOCK"
	ActionConnectorType_SAP_PHYSICALINVENTORY                  ActionConnectorType = "SAP_PHYSICALINVENTORY"
	ActionConnectorType_SAP_PRODUCTMASTERDATA                  ActionConnectorType = "SAP_PRODUCTMASTERDATA"
	ActionConnectorType_SERVICENOW_NOW_PLATFORM                ActionConnectorType = "SERVICENOW_NOW_PLATFORM"
	ActionConnectorType_SLACK                                  ActionConnectorType = "SLACK"
	ActionConnectorType_SMARTSHEET                             ActionConnectorType = "SMARTSHEET"
	ActionConnectorType_ZENDESK_SUITE                          ActionConnectorType = "ZENDESK_SUITE"
)

type AggType string

const (
	AggType_AVERAGE            AggType = "AVERAGE"
	AggType_COLUMN             AggType = "COLUMN"
	AggType_COUNT              AggType = "COUNT"
	AggType_CUSTOM             AggType = "CUSTOM"
	AggType_DISTINCT_COUNT     AggType = "DISTINCT_COUNT"
	AggType_MAX                AggType = "MAX"
	AggType_MEDIAN             AggType = "MEDIAN"
	AggType_MIN                AggType = "MIN"
	AggType_PERCENTILE         AggType = "PERCENTILE"
	AggType_PTD_AVERAGE        AggType = "PTD_AVERAGE"
	AggType_PTD_COUNT          AggType = "PTD_COUNT"
	AggType_PTD_DISTINCT_COUNT AggType = "PTD_DISTINCT_COUNT"
	AggType_PTD_MAX            AggType = "PTD_MAX"
	AggType_PTD_MIN            AggType = "PTD_MIN"
	AggType_PTD_SUM            AggType = "PTD_SUM"
	AggType_STDEV              AggType = "STDEV"
	AggType_STDEVP             AggType = "STDEVP"
	AggType_SUM                AggType = "SUM"
	AggType_VAR                AggType = "VAR"
	AggType_VARP               AggType = "VARP"
)

type AnalysisErrorType string

const (
	AnalysisErrorType_ACCESS_DENIED                   AnalysisErrorType = "ACCESS_DENIED"
	AnalysisErrorType_COLUMN_GEOGRAPHIC_ROLE_MISMATCH AnalysisErrorType = "COLUMN_GEOGRAPHIC_ROLE_MISMATCH"
	AnalysisErrorType_COLUMN_REPLACEMENT_MISSING      AnalysisErrorType = "COLUMN_REPLACEMENT_MISSING"
	AnalysisErrorType_COLUMN_TYPE_MISMATCH            AnalysisErrorType = "COLUMN_TYPE_MISMATCH"
	AnalysisErrorType_DATA_SET_NOT_FOUND              AnalysisErrorType = "DATA_SET_NOT_FOUND"
	AnalysisErrorType_INTERNAL_FAILURE                AnalysisErrorType = "INTERNAL_FAILURE"
	AnalysisErrorType_PARAMETER_NOT_FOUND             AnalysisErrorType = "PARAMETER_NOT_FOUND"
	AnalysisErrorType_PARAMETER_TYPE_INVALID          AnalysisErrorType = "PARAMETER_TYPE_INVALID"
	AnalysisErrorType_PARAMETER_VALUE_INCOMPATIBLE    AnalysisErrorType = "PARAMETER_VALUE_INCOMPATIBLE"
	AnalysisErrorType_SOURCE_NOT_FOUND                AnalysisErrorType = "SOURCE_NOT_FOUND"
)

type AnalysisFilterAttribute string

const (
	AnalysisFilterAttribute_ANALYSIS_NAME                     AnalysisFilterAttribute = "ANALYSIS_NAME"
	AnalysisFilterAttribute_DIRECT_QUICKSIGHT_OWNER           AnalysisFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	AnalysisFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      AnalysisFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	AnalysisFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER AnalysisFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	AnalysisFilterAttribute_QUICKSIGHT_OWNER                  AnalysisFilterAttribute = "QUICKSIGHT_OWNER"
	AnalysisFilterAttribute_QUICKSIGHT_USER                   AnalysisFilterAttribute = "QUICKSIGHT_USER"
	AnalysisFilterAttribute_QUICKSIGHT_VIEWER_OR_OWNER        AnalysisFilterAttribute = "QUICKSIGHT_VIEWER_OR_OWNER"
)

type AnchorOption string

const (
	AnchorOption_NOW AnchorOption = "NOW"
)

type AnchorType string

const (
	AnchorType_TODAY AnchorType = "TODAY"
)

type AnonymousUserDashboardEmbeddingConfigurationDisabledFeature string

const (
	AnonymousUserDashboardEmbeddingConfigurationDisabledFeature_SHARED_VIEW AnonymousUserDashboardEmbeddingConfigurationDisabledFeature = "SHARED_VIEW"
)

type AnonymousUserDashboardEmbeddingConfigurationEnabledFeature string

const (
	AnonymousUserDashboardEmbeddingConfigurationEnabledFeature_SHARED_VIEW AnonymousUserDashboardEmbeddingConfigurationEnabledFeature = "SHARED_VIEW"
)

type ArcThickness string

const (
	ArcThickness_LARGE  ArcThickness = "LARGE"
	ArcThickness_MEDIUM ArcThickness = "MEDIUM"
	ArcThickness_SMALL  ArcThickness = "SMALL"
	ArcThickness_WHOLE  ArcThickness = "WHOLE"
)

type ArcThicknessOptions string

const (
	ArcThicknessOptions_LARGE  ArcThicknessOptions = "LARGE"
	ArcThicknessOptions_MEDIUM ArcThicknessOptions = "MEDIUM"
	ArcThicknessOptions_SMALL  ArcThicknessOptions = "SMALL"
)

type AssetBundleExportFormat string

const (
	AssetBundleExportFormat_CLOUDFORMATION_JSON AssetBundleExportFormat = "CLOUDFORMATION_JSON"
	AssetBundleExportFormat_QUICKSIGHT_JSON     AssetBundleExportFormat = "QUICKSIGHT_JSON"
)

type AssetBundleExportJobAnalysisPropertyToOverride string

const (
	AssetBundleExportJobAnalysisPropertyToOverride_Name AssetBundleExportJobAnalysisPropertyToOverride = "Name"
)

type AssetBundleExportJobDashboardPropertyToOverride string

const (
	AssetBundleExportJobDashboardPropertyToOverride_Name AssetBundleExportJobDashboardPropertyToOverride = "Name"
)

type AssetBundleExportJobDataSetPropertyToOverride string

const (
	AssetBundleExportJobDataSetPropertyToOverride_Name                           AssetBundleExportJobDataSetPropertyToOverride = "Name"
	AssetBundleExportJobDataSetPropertyToOverride_RefreshFailureEmailAlertStatus AssetBundleExportJobDataSetPropertyToOverride = "RefreshFailureEmailAlertStatus"
)

type AssetBundleExportJobDataSourcePropertyToOverride string

const (
	AssetBundleExportJobDataSourcePropertyToOverride_Catalog              AssetBundleExportJobDataSourcePropertyToOverride = "Catalog"
	AssetBundleExportJobDataSourcePropertyToOverride_ClusterId            AssetBundleExportJobDataSourcePropertyToOverride = "ClusterId"
	AssetBundleExportJobDataSourcePropertyToOverride_DataSetName          AssetBundleExportJobDataSourcePropertyToOverride = "DataSetName"
	AssetBundleExportJobDataSourcePropertyToOverride_Database             AssetBundleExportJobDataSourcePropertyToOverride = "Database"
	AssetBundleExportJobDataSourcePropertyToOverride_DisableSsl           AssetBundleExportJobDataSourcePropertyToOverride = "DisableSsl"
	AssetBundleExportJobDataSourcePropertyToOverride_Domain               AssetBundleExportJobDataSourcePropertyToOverride = "Domain"
	AssetBundleExportJobDataSourcePropertyToOverride_Host                 AssetBundleExportJobDataSourcePropertyToOverride = "Host"
	AssetBundleExportJobDataSourcePropertyToOverride_InstanceId           AssetBundleExportJobDataSourcePropertyToOverride = "InstanceId"
	AssetBundleExportJobDataSourcePropertyToOverride_ManifestFileLocation AssetBundleExportJobDataSourcePropertyToOverride = "ManifestFileLocation"
	AssetBundleExportJobDataSourcePropertyToOverride_Name                 AssetBundleExportJobDataSourcePropertyToOverride = "Name"
	AssetBundleExportJobDataSourcePropertyToOverride_Password             AssetBundleExportJobDataSourcePropertyToOverride = "Password"
	AssetBundleExportJobDataSourcePropertyToOverride_Port                 AssetBundleExportJobDataSourcePropertyToOverride = "Port"
	AssetBundleExportJobDataSourcePropertyToOverride_ProductType          AssetBundleExportJobDataSourcePropertyToOverride = "ProductType"
	AssetBundleExportJobDataSourcePropertyToOverride_RoleArn              AssetBundleExportJobDataSourcePropertyToOverride = "RoleArn"
	AssetBundleExportJobDataSourcePropertyToOverride_SecretArn            AssetBundleExportJobDataSourcePropertyToOverride = "SecretArn"
	AssetBundleExportJobDataSourcePropertyToOverride_Username             AssetBundleExportJobDataSourcePropertyToOverride = "Username"
	AssetBundleExportJobDataSourcePropertyToOverride_Warehouse            AssetBundleExportJobDataSourcePropertyToOverride = "Warehouse"
	AssetBundleExportJobDataSourcePropertyToOverride_WorkGroup            AssetBundleExportJobDataSourcePropertyToOverride = "WorkGroup"
)

type AssetBundleExportJobFolderPropertyToOverride string

const (
	AssetBundleExportJobFolderPropertyToOverride_Name            AssetBundleExportJobFolderPropertyToOverride = "Name"
	AssetBundleExportJobFolderPropertyToOverride_ParentFolderArn AssetBundleExportJobFolderPropertyToOverride = "ParentFolderArn"
)

type AssetBundleExportJobRefreshSchedulePropertyToOverride string

const (
	AssetBundleExportJobRefreshSchedulePropertyToOverride_StartAfterDateTime AssetBundleExportJobRefreshSchedulePropertyToOverride = "StartAfterDateTime"
)

type AssetBundleExportJobStatus string

const (
	AssetBundleExportJobStatus_FAILED                         AssetBundleExportJobStatus = "FAILED"
	AssetBundleExportJobStatus_IN_PROGRESS                    AssetBundleExportJobStatus = "IN_PROGRESS"
	AssetBundleExportJobStatus_QUEUED_FOR_IMMEDIATE_EXECUTION AssetBundleExportJobStatus = "QUEUED_FOR_IMMEDIATE_EXECUTION"
	AssetBundleExportJobStatus_SUCCESSFUL                     AssetBundleExportJobStatus = "SUCCESSFUL"
)

type AssetBundleExportJobThemePropertyToOverride string

const (
	AssetBundleExportJobThemePropertyToOverride_Name AssetBundleExportJobThemePropertyToOverride = "Name"
)

type AssetBundleExportJobVPCConnectionPropertyToOverride string

const (
	AssetBundleExportJobVPCConnectionPropertyToOverride_DnsResolvers AssetBundleExportJobVPCConnectionPropertyToOverride = "DnsResolvers"
	AssetBundleExportJobVPCConnectionPropertyToOverride_Name         AssetBundleExportJobVPCConnectionPropertyToOverride = "Name"
	AssetBundleExportJobVPCConnectionPropertyToOverride_RoleArn      AssetBundleExportJobVPCConnectionPropertyToOverride = "RoleArn"
)

type AssetBundleImportFailureAction string

const (
	AssetBundleImportFailureAction_DO_NOTHING AssetBundleImportFailureAction = "DO_NOTHING"
	AssetBundleImportFailureAction_ROLLBACK   AssetBundleImportFailureAction = "ROLLBACK"
)

type AssetBundleImportJobStatus string

const (
	AssetBundleImportJobStatus_FAILED                         AssetBundleImportJobStatus = "FAILED"
	AssetBundleImportJobStatus_FAILED_ROLLBACK_COMPLETED      AssetBundleImportJobStatus = "FAILED_ROLLBACK_COMPLETED"
	AssetBundleImportJobStatus_FAILED_ROLLBACK_ERROR          AssetBundleImportJobStatus = "FAILED_ROLLBACK_ERROR"
	AssetBundleImportJobStatus_FAILED_ROLLBACK_IN_PROGRESS    AssetBundleImportJobStatus = "FAILED_ROLLBACK_IN_PROGRESS"
	AssetBundleImportJobStatus_IN_PROGRESS                    AssetBundleImportJobStatus = "IN_PROGRESS"
	AssetBundleImportJobStatus_QUEUED_FOR_IMMEDIATE_EXECUTION AssetBundleImportJobStatus = "QUEUED_FOR_IMMEDIATE_EXECUTION"
	AssetBundleImportJobStatus_SUCCESSFUL                     AssetBundleImportJobStatus = "SUCCESSFUL"
)

type AssignmentStatus string

const (
	AssignmentStatus_DISABLED AssignmentStatus = "DISABLED"
	AssignmentStatus_DRAFT    AssignmentStatus = "DRAFT"
	AssignmentStatus_ENABLED  AssignmentStatus = "ENABLED"
)

type AuthenticationMethodOption string

const (
	AuthenticationMethodOption_ACTIVE_DIRECTORY    AuthenticationMethodOption = "ACTIVE_DIRECTORY"
	AuthenticationMethodOption_IAM_AND_QUICKSIGHT  AuthenticationMethodOption = "IAM_AND_QUICKSIGHT"
	AuthenticationMethodOption_IAM_IDENTITY_CENTER AuthenticationMethodOption = "IAM_IDENTITY_CENTER"
	AuthenticationMethodOption_IAM_ONLY            AuthenticationMethodOption = "IAM_ONLY"
)

type AuthenticationType string

const (
	AuthenticationType_PASSWORD AuthenticationType = "PASSWORD"
	AuthenticationType_TOKEN    AuthenticationType = "TOKEN"
	AuthenticationType_X509     AuthenticationType = "X509"
)

type AuthorSpecifiedAggregation string

const (
	AuthorSpecifiedAggregation_AVERAGE        AuthorSpecifiedAggregation = "AVERAGE"
	AuthorSpecifiedAggregation_COUNT          AuthorSpecifiedAggregation = "COUNT"
	AuthorSpecifiedAggregation_DISTINCT_COUNT AuthorSpecifiedAggregation = "DISTINCT_COUNT"
	AuthorSpecifiedAggregation_MAX            AuthorSpecifiedAggregation = "MAX"
	AuthorSpecifiedAggregation_MEDIAN         AuthorSpecifiedAggregation = "MEDIAN"
	AuthorSpecifiedAggregation_MIN            AuthorSpecifiedAggregation = "MIN"
	AuthorSpecifiedAggregation_PERCENTILE     AuthorSpecifiedAggregation = "PERCENTILE"
	AuthorSpecifiedAggregation_STDEV          AuthorSpecifiedAggregation = "STDEV"
	AuthorSpecifiedAggregation_STDEVP         AuthorSpecifiedAggregation = "STDEVP"
	AuthorSpecifiedAggregation_SUM            AuthorSpecifiedAggregation = "SUM"
	AuthorSpecifiedAggregation_VAR            AuthorSpecifiedAggregation = "VAR"
	AuthorSpecifiedAggregation_VARP           AuthorSpecifiedAggregation = "VARP"
)

type AuthorizationCodeGrantCredentialsSource string

const (
	AuthorizationCodeGrantCredentialsSource_PLAIN_CREDENTIALS AuthorizationCodeGrantCredentialsSource = "PLAIN_CREDENTIALS"
)

type AxisBinding string

const (
	AxisBinding_PRIMARY_YAXIS   AxisBinding = "PRIMARY_YAXIS"
	AxisBinding_SECONDARY_YAXIS AxisBinding = "SECONDARY_YAXIS"
)

type BarChartOrientation string

const (
	BarChartOrientation_HORIZONTAL BarChartOrientation = "HORIZONTAL"
	BarChartOrientation_VERTICAL   BarChartOrientation = "VERTICAL"
)

type BarsArrangement string

const (
	BarsArrangement_CLUSTERED       BarsArrangement = "CLUSTERED"
	BarsArrangement_STACKED         BarsArrangement = "STACKED"
	BarsArrangement_STACKED_PERCENT BarsArrangement = "STACKED_PERCENT"
)

type BaseMapStyleType string

const (
	BaseMapStyleType_DARK_GRAY  BaseMapStyleType = "DARK_GRAY"
	BaseMapStyleType_IMAGERY    BaseMapStyleType = "IMAGERY"
	BaseMapStyleType_LIGHT_GRAY BaseMapStyleType = "LIGHT_GRAY"
	BaseMapStyleType_STREET     BaseMapStyleType = "STREET"
)

type BoxPlotFillStyle string

const (
	BoxPlotFillStyle_SOLID       BoxPlotFillStyle = "SOLID"
	BoxPlotFillStyle_TRANSPARENT BoxPlotFillStyle = "TRANSPARENT"
)

type BrandStatus string

const (
	BrandStatus_CREATE_FAILED      BrandStatus = "CREATE_FAILED"
	BrandStatus_CREATE_IN_PROGRESS BrandStatus = "CREATE_IN_PROGRESS"
	BrandStatus_CREATE_SUCCEEDED   BrandStatus = "CREATE_SUCCEEDED"
	BrandStatus_DELETE_FAILED      BrandStatus = "DELETE_FAILED"
	BrandStatus_DELETE_IN_PROGRESS BrandStatus = "DELETE_IN_PROGRESS"
)

type BrandVersionStatus string

const (
	BrandVersionStatus_CREATE_FAILED      BrandVersionStatus = "CREATE_FAILED"
	BrandVersionStatus_CREATE_IN_PROGRESS BrandVersionStatus = "CREATE_IN_PROGRESS"
	BrandVersionStatus_CREATE_SUCCEEDED   BrandVersionStatus = "CREATE_SUCCEEDED"
)

type CapabilityState string

const (
	CapabilityState_DENY CapabilityState = "DENY"
)

type CategoricalAggregationFunction string

const (
	CategoricalAggregationFunction_COUNT          CategoricalAggregationFunction = "COUNT"
	CategoricalAggregationFunction_DISTINCT_COUNT CategoricalAggregationFunction = "DISTINCT_COUNT"
)

type CategoryFilterFunction string

const (
	CategoryFilterFunction_CONTAINS CategoryFilterFunction = "CONTAINS"
	CategoryFilterFunction_EXACT    CategoryFilterFunction = "EXACT"
)

type CategoryFilterMatchOperator string

const (
	CategoryFilterMatchOperator_CONTAINS         CategoryFilterMatchOperator = "CONTAINS"
	CategoryFilterMatchOperator_DOES_NOT_CONTAIN CategoryFilterMatchOperator = "DOES_NOT_CONTAIN"
	CategoryFilterMatchOperator_DOES_NOT_EQUAL   CategoryFilterMatchOperator = "DOES_NOT_EQUAL"
	CategoryFilterMatchOperator_ENDS_WITH        CategoryFilterMatchOperator = "ENDS_WITH"
	CategoryFilterMatchOperator_EQUALS           CategoryFilterMatchOperator = "EQUALS"
	CategoryFilterMatchOperator_STARTS_WITH      CategoryFilterMatchOperator = "STARTS_WITH"
)

type CategoryFilterSelectAllOptions string

const (
	CategoryFilterSelectAllOptions_FILTER_ALL_VALUES CategoryFilterSelectAllOptions = "FILTER_ALL_VALUES"
)

type CategoryFilterType string

const (
	CategoryFilterType_CUSTOM_FILTER      CategoryFilterType = "CUSTOM_FILTER"
	CategoryFilterType_CUSTOM_FILTER_LIST CategoryFilterType = "CUSTOM_FILTER_LIST"
	CategoryFilterType_FILTER_LIST        CategoryFilterType = "FILTER_LIST"
)

type ClientCredentialsSource string

const (
	ClientCredentialsSource_PLAIN_CREDENTIALS ClientCredentialsSource = "PLAIN_CREDENTIALS"
)

type ColorFillType string

const (
	ColorFillType_DISCRETE ColorFillType = "DISCRETE"
	ColorFillType_GRADIENT ColorFillType = "GRADIENT"
)

type ColumnDataRole string

const (
	ColumnDataRole_DIMENSION ColumnDataRole = "DIMENSION"
	ColumnDataRole_MEASURE   ColumnDataRole = "MEASURE"
)

type ColumnDataSubType string

const (
	ColumnDataSubType_FIXED ColumnDataSubType = "FIXED"
	ColumnDataSubType_FLOAT ColumnDataSubType = "FLOAT"
)

type ColumnDataType string

const (
	ColumnDataType_DATETIME ColumnDataType = "DATETIME"
	ColumnDataType_DECIMAL  ColumnDataType = "DECIMAL"
	ColumnDataType_INTEGER  ColumnDataType = "INTEGER"
	ColumnDataType_STRING   ColumnDataType = "STRING"
)

type ColumnOrderingType string

const (
	ColumnOrderingType_GREATER_IS_BETTER ColumnOrderingType = "GREATER_IS_BETTER"
	ColumnOrderingType_LESSER_IS_BETTER  ColumnOrderingType = "LESSER_IS_BETTER"
	ColumnOrderingType_SPECIFIED         ColumnOrderingType = "SPECIFIED"
)

type ColumnRole string

const (
	ColumnRole_DIMENSION ColumnRole = "DIMENSION"
	ColumnRole_MEASURE   ColumnRole = "MEASURE"
)

type ColumnTagName string

const (
	ColumnTagName_COLUMN_DESCRIPTION     ColumnTagName = "COLUMN_DESCRIPTION"
	ColumnTagName_COLUMN_GEOGRAPHIC_ROLE ColumnTagName = "COLUMN_GEOGRAPHIC_ROLE"
)

type CommitMode string

const (
	CommitMode_AUTO   CommitMode = "AUTO"
	CommitMode_MANUAL CommitMode = "MANUAL"
)

type ComparisonMethod string

const (
	ComparisonMethod_DIFFERENCE         ComparisonMethod = "DIFFERENCE"
	ComparisonMethod_PERCENT            ComparisonMethod = "PERCENT"
	ComparisonMethod_PERCENT_DIFFERENCE ComparisonMethod = "PERCENT_DIFFERENCE"
)

type ComparisonMethodType string

const (
	ComparisonMethodType_DIFF                      ComparisonMethodType = "DIFF"
	ComparisonMethodType_DIFF_AS_PERC              ComparisonMethodType = "DIFF_AS_PERC"
	ComparisonMethodType_MOVING_AVERAGE            ComparisonMethodType = "MOVING_AVERAGE"
	ComparisonMethodType_PERCENT_OF_TOTAL          ComparisonMethodType = "PERCENT_OF_TOTAL"
	ComparisonMethodType_PERC_DIFF                 ComparisonMethodType = "PERC_DIFF"
	ComparisonMethodType_POP_CURRENT_DIFF          ComparisonMethodType = "POP_CURRENT_DIFF"
	ComparisonMethodType_POP_CURRENT_DIFF_AS_PERC  ComparisonMethodType = "POP_CURRENT_DIFF_AS_PERC"
	ComparisonMethodType_POP_OVERTIME_DIFF         ComparisonMethodType = "POP_OVERTIME_DIFF"
	ComparisonMethodType_POP_OVERTIME_DIFF_AS_PERC ComparisonMethodType = "POP_OVERTIME_DIFF_AS_PERC"
	ComparisonMethodType_RUNNING_SUM               ComparisonMethodType = "RUNNING_SUM"
)

type ConditionalFormattingIconDisplayOption string

const (
	ConditionalFormattingIconDisplayOption_ICON_ONLY ConditionalFormattingIconDisplayOption = "ICON_ONLY"
)

type ConditionalFormattingIconSetType string

const (
	ConditionalFormattingIconSetType_BARS                ConditionalFormattingIconSetType = "BARS"
	ConditionalFormattingIconSetType_CARET_UP_MINUS_DOWN ConditionalFormattingIconSetType = "CARET_UP_MINUS_DOWN"
	ConditionalFormattingIconSetType_CHECK_X             ConditionalFormattingIconSetType = "CHECK_X"
	ConditionalFormattingIconSetType_FLAGS               ConditionalFormattingIconSetType = "FLAGS"
	ConditionalFormattingIconSetType_FOUR_COLOR_ARROW    ConditionalFormattingIconSetType = "FOUR_COLOR_ARROW"
	ConditionalFormattingIconSetType_FOUR_GRAY_ARROW     ConditionalFormattingIconSetType = "FOUR_GRAY_ARROW"
	ConditionalFormattingIconSetType_PLUS_MINUS          ConditionalFormattingIconSetType = "PLUS_MINUS"
	ConditionalFormattingIconSetType_THREE_CIRCLE        ConditionalFormattingIconSetType = "THREE_CIRCLE"
	ConditionalFormattingIconSetType_THREE_COLOR_ARROW   ConditionalFormattingIconSetType = "THREE_COLOR_ARROW"
	ConditionalFormattingIconSetType_THREE_GRAY_ARROW    ConditionalFormattingIconSetType = "THREE_GRAY_ARROW"
	ConditionalFormattingIconSetType_THREE_SHAPE         ConditionalFormattingIconSetType = "THREE_SHAPE"
)

type ConnectionAuthType string

const (
	ConnectionAuthType_API_KEY                   ConnectionAuthType = "API_KEY"
	ConnectionAuthType_BASIC                     ConnectionAuthType = "BASIC"
	ConnectionAuthType_IAM                       ConnectionAuthType = "IAM"
	ConnectionAuthType_NONE                      ConnectionAuthType = "NONE"
	ConnectionAuthType_OAUTH2_AUTHORIZATION_CODE ConnectionAuthType = "OAUTH2_AUTHORIZATION_CODE"
	ConnectionAuthType_OAUTH2_CLIENT_CREDENTIALS ConnectionAuthType = "OAUTH2_CLIENT_CREDENTIALS"
)

type ConstantType string

const (
	ConstantType_COLLECTIVE ConstantType = "COLLECTIVE"
	ConstantType_RANGE      ConstantType = "RANGE"
	ConstantType_SINGULAR   ConstantType = "SINGULAR"
)

type ContributionAnalysisDirection string

const (
	ContributionAnalysisDirection_DECREASE ContributionAnalysisDirection = "DECREASE"
	ContributionAnalysisDirection_INCREASE ContributionAnalysisDirection = "INCREASE"
	ContributionAnalysisDirection_NEUTRAL  ContributionAnalysisDirection = "NEUTRAL"
)

type ContributionAnalysisSortType string

const (
	ContributionAnalysisSortType_ABSOLUTE_DIFFERENCE     ContributionAnalysisSortType = "ABSOLUTE_DIFFERENCE"
	ContributionAnalysisSortType_CONTRIBUTION_PERCENTAGE ContributionAnalysisSortType = "CONTRIBUTION_PERCENTAGE"
	ContributionAnalysisSortType_DEVIATION_FROM_EXPECTED ContributionAnalysisSortType = "DEVIATION_FROM_EXPECTED"
	ContributionAnalysisSortType_PERCENTAGE_DIFFERENCE   ContributionAnalysisSortType = "PERCENTAGE_DIFFERENCE"
)

type CrossDatasetTypes string

const (
	CrossDatasetTypes_ALL_DATASETS   CrossDatasetTypes = "ALL_DATASETS"
	CrossDatasetTypes_SINGLE_DATASET CrossDatasetTypes = "SINGLE_DATASET"
)

type CustomContentImageScalingConfiguration string

const (
	CustomContentImageScalingConfiguration_DO_NOT_SCALE    CustomContentImageScalingConfiguration = "DO_NOT_SCALE"
	CustomContentImageScalingConfiguration_FIT_TO_HEIGHT   CustomContentImageScalingConfiguration = "FIT_TO_HEIGHT"
	CustomContentImageScalingConfiguration_FIT_TO_WIDTH    CustomContentImageScalingConfiguration = "FIT_TO_WIDTH"
	CustomContentImageScalingConfiguration_SCALE_TO_VISUAL CustomContentImageScalingConfiguration = "SCALE_TO_VISUAL"
)

type CustomContentType string

const (
	CustomContentType_IMAGE                  CustomContentType = "IMAGE"
	CustomContentType_OTHER_EMBEDDED_CONTENT CustomContentType = "OTHER_EMBEDDED_CONTENT"
)

type DashboardBehavior string

const (
	DashboardBehavior_DISABLED DashboardBehavior = "DISABLED"
	DashboardBehavior_ENABLED  DashboardBehavior = "ENABLED"
)

type DashboardErrorType string

const (
	DashboardErrorType_ACCESS_DENIED                   DashboardErrorType = "ACCESS_DENIED"
	DashboardErrorType_COLUMN_GEOGRAPHIC_ROLE_MISMATCH DashboardErrorType = "COLUMN_GEOGRAPHIC_ROLE_MISMATCH"
	DashboardErrorType_COLUMN_REPLACEMENT_MISSING      DashboardErrorType = "COLUMN_REPLACEMENT_MISSING"
	DashboardErrorType_COLUMN_TYPE_MISMATCH            DashboardErrorType = "COLUMN_TYPE_MISMATCH"
	DashboardErrorType_DATA_SET_NOT_FOUND              DashboardErrorType = "DATA_SET_NOT_FOUND"
	DashboardErrorType_INTERNAL_FAILURE                DashboardErrorType = "INTERNAL_FAILURE"
	DashboardErrorType_PARAMETER_NOT_FOUND             DashboardErrorType = "PARAMETER_NOT_FOUND"
	DashboardErrorType_PARAMETER_TYPE_INVALID          DashboardErrorType = "PARAMETER_TYPE_INVALID"
	DashboardErrorType_PARAMETER_VALUE_INCOMPATIBLE    DashboardErrorType = "PARAMETER_VALUE_INCOMPATIBLE"
	DashboardErrorType_SOURCE_NOT_FOUND                DashboardErrorType = "SOURCE_NOT_FOUND"
)

type DashboardFilterAttribute string

const (
	DashboardFilterAttribute_DASHBOARD_NAME                    DashboardFilterAttribute = "DASHBOARD_NAME"
	DashboardFilterAttribute_DIRECT_QUICKSIGHT_OWNER           DashboardFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	DashboardFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      DashboardFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	DashboardFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER DashboardFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	DashboardFilterAttribute_QUICKSIGHT_OWNER                  DashboardFilterAttribute = "QUICKSIGHT_OWNER"
	DashboardFilterAttribute_QUICKSIGHT_USER                   DashboardFilterAttribute = "QUICKSIGHT_USER"
	DashboardFilterAttribute_QUICKSIGHT_VIEWER_OR_OWNER        DashboardFilterAttribute = "QUICKSIGHT_VIEWER_OR_OWNER"
)

type DashboardUIState string

const (
	DashboardUIState_COLLAPSED DashboardUIState = "COLLAPSED"
	DashboardUIState_EXPANDED  DashboardUIState = "EXPANDED"
)

type DashboardsQAStatus string

const (
	DashboardsQAStatus_DISABLED DashboardsQAStatus = "DISABLED"
	DashboardsQAStatus_ENABLED  DashboardsQAStatus = "ENABLED"
)

type DataLabelContent string

const (
	DataLabelContent_PERCENT           DataLabelContent = "PERCENT"
	DataLabelContent_VALUE             DataLabelContent = "VALUE"
	DataLabelContent_VALUE_AND_PERCENT DataLabelContent = "VALUE_AND_PERCENT"
)

type DataLabelOverlap string

const (
	DataLabelOverlap_DISABLE_OVERLAP DataLabelOverlap = "DISABLE_OVERLAP"
	DataLabelOverlap_ENABLE_OVERLAP  DataLabelOverlap = "ENABLE_OVERLAP"
)

type DataLabelPosition string

const (
	DataLabelPosition_BOTTOM  DataLabelPosition = "BOTTOM"
	DataLabelPosition_INSIDE  DataLabelPosition = "INSIDE"
	DataLabelPosition_LEFT    DataLabelPosition = "LEFT"
	DataLabelPosition_OUTSIDE DataLabelPosition = "OUTSIDE"
	DataLabelPosition_RIGHT   DataLabelPosition = "RIGHT"
	DataLabelPosition_TOP     DataLabelPosition = "TOP"
)

type DataPrepSimpleAggregationFunctionType string

const (
	DataPrepSimpleAggregationFunctionType_AVERAGE        DataPrepSimpleAggregationFunctionType = "AVERAGE"
	DataPrepSimpleAggregationFunctionType_COUNT          DataPrepSimpleAggregationFunctionType = "COUNT"
	DataPrepSimpleAggregationFunctionType_DISTINCT_COUNT DataPrepSimpleAggregationFunctionType = "DISTINCT_COUNT"
	DataPrepSimpleAggregationFunctionType_MAX            DataPrepSimpleAggregationFunctionType = "MAX"
	DataPrepSimpleAggregationFunctionType_MIN            DataPrepSimpleAggregationFunctionType = "MIN"
	DataPrepSimpleAggregationFunctionType_SUM            DataPrepSimpleAggregationFunctionType = "SUM"
)

type DataSetDateComparisonFilterOperator string

const (
	DataSetDateComparisonFilterOperator_AFTER               DataSetDateComparisonFilterOperator = "AFTER"
	DataSetDateComparisonFilterOperator_AFTER_OR_EQUALS_TO  DataSetDateComparisonFilterOperator = "AFTER_OR_EQUALS_TO"
	DataSetDateComparisonFilterOperator_BEFORE              DataSetDateComparisonFilterOperator = "BEFORE"
	DataSetDateComparisonFilterOperator_BEFORE_OR_EQUALS_TO DataSetDateComparisonFilterOperator = "BEFORE_OR_EQUALS_TO"
)

type DataSetFilterAttribute string

const (
	DataSetFilterAttribute_DATASET_NAME                      DataSetFilterAttribute = "DATASET_NAME"
	DataSetFilterAttribute_DIRECT_QUICKSIGHT_OWNER           DataSetFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	DataSetFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      DataSetFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	DataSetFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER DataSetFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	DataSetFilterAttribute_QUICKSIGHT_OWNER                  DataSetFilterAttribute = "QUICKSIGHT_OWNER"
	DataSetFilterAttribute_QUICKSIGHT_VIEWER_OR_OWNER        DataSetFilterAttribute = "QUICKSIGHT_VIEWER_OR_OWNER"
)

type DataSetImportMode string

const (
	DataSetImportMode_DIRECT_QUERY DataSetImportMode = "DIRECT_QUERY"
	DataSetImportMode_SPICE        DataSetImportMode = "SPICE"
)

type DataSetNumericComparisonFilterOperator string

const (
	DataSetNumericComparisonFilterOperator_DOES_NOT_EQUAL            DataSetNumericComparisonFilterOperator = "DOES_NOT_EQUAL"
	DataSetNumericComparisonFilterOperator_EQUALS                    DataSetNumericComparisonFilterOperator = "EQUALS"
	DataSetNumericComparisonFilterOperator_GREATER_THAN              DataSetNumericComparisonFilterOperator = "GREATER_THAN"
	DataSetNumericComparisonFilterOperator_GREATER_THAN_OR_EQUALS_TO DataSetNumericComparisonFilterOperator = "GREATER_THAN_OR_EQUALS_TO"
	DataSetNumericComparisonFilterOperator_LESS_THAN                 DataSetNumericComparisonFilterOperator = "LESS_THAN"
	DataSetNumericComparisonFilterOperator_LESS_THAN_OR_EQUALS_TO    DataSetNumericComparisonFilterOperator = "LESS_THAN_OR_EQUALS_TO"
)

type DataSetStringComparisonFilterOperator string

const (
	DataSetStringComparisonFilterOperator_CONTAINS         DataSetStringComparisonFilterOperator = "CONTAINS"
	DataSetStringComparisonFilterOperator_DOES_NOT_CONTAIN DataSetStringComparisonFilterOperator = "DOES_NOT_CONTAIN"
	DataSetStringComparisonFilterOperator_DOES_NOT_EQUAL   DataSetStringComparisonFilterOperator = "DOES_NOT_EQUAL"
	DataSetStringComparisonFilterOperator_ENDS_WITH        DataSetStringComparisonFilterOperator = "ENDS_WITH"
	DataSetStringComparisonFilterOperator_EQUALS           DataSetStringComparisonFilterOperator = "EQUALS"
	DataSetStringComparisonFilterOperator_STARTS_WITH      DataSetStringComparisonFilterOperator = "STARTS_WITH"
)

type DataSetStringListFilterOperator string

const (
	DataSetStringListFilterOperator_EXCLUDE DataSetStringListFilterOperator = "EXCLUDE"
	DataSetStringListFilterOperator_INCLUDE DataSetStringListFilterOperator = "INCLUDE"
)

type DataSetUseAs string

const (
	DataSetUseAs_RLS_RULES DataSetUseAs = "RLS_RULES"
)

type DataSourceErrorInfoType string

const (
	DataSourceErrorInfoType_ACCESS_DENIED                DataSourceErrorInfoType = "ACCESS_DENIED"
	DataSourceErrorInfoType_CONFLICT                     DataSourceErrorInfoType = "CONFLICT"
	DataSourceErrorInfoType_COPY_SOURCE_NOT_FOUND        DataSourceErrorInfoType = "COPY_SOURCE_NOT_FOUND"
	DataSourceErrorInfoType_ENGINE_VERSION_NOT_SUPPORTED DataSourceErrorInfoType = "ENGINE_VERSION_NOT_SUPPORTED"
	DataSourceErrorInfoType_GENERIC_SQL_FAILURE          DataSourceErrorInfoType = "GENERIC_SQL_FAILURE"
	DataSourceErrorInfoType_TIMEOUT                      DataSourceErrorInfoType = "TIMEOUT"
	DataSourceErrorInfoType_UNKNOWN                      DataSourceErrorInfoType = "UNKNOWN"
	DataSourceErrorInfoType_UNKNOWN_HOST                 DataSourceErrorInfoType = "UNKNOWN_HOST"
)

type DataSourceFilterAttribute string

const (
	DataSourceFilterAttribute_DATASOURCE_NAME                   DataSourceFilterAttribute = "DATASOURCE_NAME"
	DataSourceFilterAttribute_DIRECT_QUICKSIGHT_OWNER           DataSourceFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	DataSourceFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      DataSourceFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	DataSourceFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER DataSourceFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
)

type DataSourceType string

const (
	DataSourceType_ADOBE_ANALYTICS      DataSourceType = "ADOBE_ANALYTICS"
	DataSourceType_AMAZON_ELASTICSEARCH DataSourceType = "AMAZON_ELASTICSEARCH"
	DataSourceType_AMAZON_OPENSEARCH    DataSourceType = "AMAZON_OPENSEARCH"
	DataSourceType_ATHENA               DataSourceType = "ATHENA"
	DataSourceType_AURORA               DataSourceType = "AURORA"
	DataSourceType_AURORA_POSTGRESQL    DataSourceType = "AURORA_POSTGRESQL"
	DataSourceType_AWS_IOT_ANALYTICS    DataSourceType = "AWS_IOT_ANALYTICS"
	DataSourceType_BIGQUERY             DataSourceType = "BIGQUERY"
	DataSourceType_CONFLUENCE           DataSourceType = "CONFLUENCE"
	DataSourceType_DATABRICKS           DataSourceType = "DATABRICKS"
	DataSourceType_EXASOL               DataSourceType = "EXASOL"
	DataSourceType_GITHUB               DataSourceType = "GITHUB"
	DataSourceType_GOOGLESHEETS         DataSourceType = "GOOGLESHEETS"
	DataSourceType_GOOGLE_DRIVE         DataSourceType = "GOOGLE_DRIVE"
	DataSourceType_JIRA                 DataSourceType = "JIRA"
	DataSourceType_MARIADB              DataSourceType = "MARIADB"
	DataSourceType_MYSQL                DataSourceType = "MYSQL"
	DataSourceType_ONE_DRIVE            DataSourceType = "ONE_DRIVE"
	DataSourceType_ORACLE               DataSourceType = "ORACLE"
	DataSourceType_POSTGRESQL           DataSourceType = "POSTGRESQL"
	DataSourceType_PRESTO               DataSourceType = "PRESTO"
	DataSourceType_QBUSINESS            DataSourceType = "QBUSINESS"
	DataSourceType_REDSHIFT             DataSourceType = "REDSHIFT"
	DataSourceType_S3                   DataSourceType = "S3"
	DataSourceType_S3_KNOWLEDGE_BASE    DataSourceType = "S3_KNOWLEDGE_BASE"
	DataSourceType_SALESFORCE           DataSourceType = "SALESFORCE"
	DataSourceType_SERVICENOW           DataSourceType = "SERVICENOW"
	DataSourceType_SHAREPOINT           DataSourceType = "SHAREPOINT"
	DataSourceType_SNOWFLAKE            DataSourceType = "SNOWFLAKE"
	DataSourceType_SPARK                DataSourceType = "SPARK"
	DataSourceType_SQLSERVER            DataSourceType = "SQLSERVER"
	DataSourceType_STARBURST            DataSourceType = "STARBURST"
	DataSourceType_TERADATA             DataSourceType = "TERADATA"
	DataSourceType_TIMESTREAM           DataSourceType = "TIMESTREAM"
	DataSourceType_TRINO                DataSourceType = "TRINO"
	DataSourceType_TWITTER              DataSourceType = "TWITTER"
	DataSourceType_WEB_CRAWLER          DataSourceType = "WEB_CRAWLER"
)

type DatasetParameterValueType string

const (
	DatasetParameterValueType_MULTI_VALUED  DatasetParameterValueType = "MULTI_VALUED"
	DatasetParameterValueType_SINGLE_VALUED DatasetParameterValueType = "SINGLE_VALUED"
)

type DateAggregationFunction string

const (
	DateAggregationFunction_COUNT          DateAggregationFunction = "COUNT"
	DateAggregationFunction_DISTINCT_COUNT DateAggregationFunction = "DISTINCT_COUNT"
	DateAggregationFunction_MAX            DateAggregationFunction = "MAX"
	DateAggregationFunction_MIN            DateAggregationFunction = "MIN"
)

type DayOfTheWeek string

const (
	DayOfTheWeek_FRIDAY    DayOfTheWeek = "FRIDAY"
	DayOfTheWeek_MONDAY    DayOfTheWeek = "MONDAY"
	DayOfTheWeek_SATURDAY  DayOfTheWeek = "SATURDAY"
	DayOfTheWeek_SUNDAY    DayOfTheWeek = "SUNDAY"
	DayOfTheWeek_THURSDAY  DayOfTheWeek = "THURSDAY"
	DayOfTheWeek_TUESDAY   DayOfTheWeek = "TUESDAY"
	DayOfTheWeek_WEDNESDAY DayOfTheWeek = "WEDNESDAY"
)

type DayOfWeek string

const (
	DayOfWeek_FRIDAY    DayOfWeek = "FRIDAY"
	DayOfWeek_MONDAY    DayOfWeek = "MONDAY"
	DayOfWeek_SATURDAY  DayOfWeek = "SATURDAY"
	DayOfWeek_SUNDAY    DayOfWeek = "SUNDAY"
	DayOfWeek_THURSDAY  DayOfWeek = "THURSDAY"
	DayOfWeek_TUESDAY   DayOfWeek = "TUESDAY"
	DayOfWeek_WEDNESDAY DayOfWeek = "WEDNESDAY"
)

type DefaultAggregation string

const (
	DefaultAggregation_AVERAGE        DefaultAggregation = "AVERAGE"
	DefaultAggregation_COUNT          DefaultAggregation = "COUNT"
	DefaultAggregation_DISTINCT_COUNT DefaultAggregation = "DISTINCT_COUNT"
	DefaultAggregation_MAX            DefaultAggregation = "MAX"
	DefaultAggregation_MEDIAN         DefaultAggregation = "MEDIAN"
	DefaultAggregation_MIN            DefaultAggregation = "MIN"
	DefaultAggregation_STDEV          DefaultAggregation = "STDEV"
	DefaultAggregation_STDEVP         DefaultAggregation = "STDEVP"
	DefaultAggregation_SUM            DefaultAggregation = "SUM"
	DefaultAggregation_VAR            DefaultAggregation = "VAR"
	DefaultAggregation_VARP           DefaultAggregation = "VARP"
)

type DigitGroupingStyle string

const (
	DigitGroupingStyle_DEFAULT DigitGroupingStyle = "DEFAULT"
	DigitGroupingStyle_LAKHS   DigitGroupingStyle = "LAKHS"
)

type DisplayFormat string

const (
	DisplayFormat_AUTO     DisplayFormat = "AUTO"
	DisplayFormat_CURRENCY DisplayFormat = "CURRENCY"
	DisplayFormat_DATE     DisplayFormat = "DATE"
	DisplayFormat_NUMBER   DisplayFormat = "NUMBER"
	DisplayFormat_PERCENT  DisplayFormat = "PERCENT"
	DisplayFormat_STRING   DisplayFormat = "STRING"
)

type Edition string

const (
	Edition_ENTERPRISE       Edition = "ENTERPRISE"
	Edition_ENTERPRISE_AND_Q Edition = "ENTERPRISE_AND_Q"
	Edition_STANDARD         Edition = "STANDARD"
)

type EmbeddingIdentityType string

const (
	EmbeddingIdentityType_ANONYMOUS  EmbeddingIdentityType = "ANONYMOUS"
	EmbeddingIdentityType_IAM        EmbeddingIdentityType = "IAM"
	EmbeddingIdentityType_QUICKSIGHT EmbeddingIdentityType = "QUICKSIGHT"
)

type ExceptionResourceType string

const (
	ExceptionResourceType_ACCOUNT_SETTINGS     ExceptionResourceType = "ACCOUNT_SETTINGS"
	ExceptionResourceType_DATA_SET             ExceptionResourceType = "DATA_SET"
	ExceptionResourceType_DATA_SOURCE          ExceptionResourceType = "DATA_SOURCE"
	ExceptionResourceType_GROUP                ExceptionResourceType = "GROUP"
	ExceptionResourceType_IAMPOLICY_ASSIGNMENT ExceptionResourceType = "IAMPOLICY_ASSIGNMENT"
	ExceptionResourceType_INGESTION            ExceptionResourceType = "INGESTION"
	ExceptionResourceType_NAMESPACE            ExceptionResourceType = "NAMESPACE"
	ExceptionResourceType_USER                 ExceptionResourceType = "USER"
	ExceptionResourceType_VPC_CONNECTION       ExceptionResourceType = "VPC_CONNECTION"
)

type FieldName string

const (
	FieldName_DIRECT_QUICKSIGHT_OWNER           FieldName = "DIRECT_QUICKSIGHT_OWNER"
	FieldName_DIRECT_QUICKSIGHT_SOLE_OWNER      FieldName = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	FieldName_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER FieldName = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	FieldName_assetDescription                  FieldName = "assetDescription"
	FieldName_assetName                         FieldName = "assetName"
)

type FileFormat string

const (
	FileFormat_CLF  FileFormat = "CLF"
	FileFormat_CSV  FileFormat = "CSV"
	FileFormat_ELF  FileFormat = "ELF"
	FileFormat_JSON FileFormat = "JSON"
	FileFormat_TSV  FileFormat = "TSV"
	FileFormat_XLSX FileFormat = "XLSX"
)

type FilterClass string

const (
	FilterClass_CONDITIONAL_VALUE_FILTER FilterClass = "CONDITIONAL_VALUE_FILTER"
	FilterClass_ENFORCED_VALUE_FILTER    FilterClass = "ENFORCED_VALUE_FILTER"
	FilterClass_NAMED_VALUE_FILTER       FilterClass = "NAMED_VALUE_FILTER"
)

type FilterNullOption string

const (
	FilterNullOption_ALL_VALUES     FilterNullOption = "ALL_VALUES"
	FilterNullOption_NON_NULLS_ONLY FilterNullOption = "NON_NULLS_ONLY"
	FilterNullOption_NULLS_ONLY     FilterNullOption = "NULLS_ONLY"
)

type FilterOperator string

const (
	FilterOperator_StringEquals FilterOperator = "StringEquals"
	FilterOperator_StringLike   FilterOperator = "StringLike"
)

type FilterVisualScope string

const (
	FilterVisualScope_ALL_VISUALS      FilterVisualScope = "ALL_VISUALS"
	FilterVisualScope_SELECTED_VISUALS FilterVisualScope = "SELECTED_VISUALS"
)

type FlowPublishState string

const (
	FlowPublishState_DRAFT            FlowPublishState = "DRAFT"
	FlowPublishState_PENDING_APPROVAL FlowPublishState = "PENDING_APPROVAL"
	FlowPublishState_PUBLISHED        FlowPublishState = "PUBLISHED"
)

type FolderFilterAttribute string

const (
	FolderFilterAttribute_DIRECT_QUICKSIGHT_OWNER           FolderFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	FolderFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      FolderFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	FolderFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER FolderFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	FolderFilterAttribute_FOLDER_NAME                       FolderFilterAttribute = "FOLDER_NAME"
	FolderFilterAttribute_PARENT_FOLDER_ARN                 FolderFilterAttribute = "PARENT_FOLDER_ARN"
	FolderFilterAttribute_QUICKSIGHT_OWNER                  FolderFilterAttribute = "QUICKSIGHT_OWNER"
	FolderFilterAttribute_QUICKSIGHT_VIEWER_OR_OWNER        FolderFilterAttribute = "QUICKSIGHT_VIEWER_OR_OWNER"
)

type FolderType string

const (
	FolderType_RESTRICTED FolderType = "RESTRICTED"
	FolderType_SHARED     FolderType = "SHARED"
)

type FontDecoration string

const (
	FontDecoration_NONE      FontDecoration = "NONE"
	FontDecoration_UNDERLINE FontDecoration = "UNDERLINE"
)

type FontStyle string

const (
	FontStyle_ITALIC FontStyle = "ITALIC"
	FontStyle_NORMAL FontStyle = "NORMAL"
)

type FontWeightName string

const (
	FontWeightName_BOLD   FontWeightName = "BOLD"
	FontWeightName_NORMAL FontWeightName = "NORMAL"
)

type ForecastComputationSeasonality string

const (
	ForecastComputationSeasonality_AUTOMATIC ForecastComputationSeasonality = "AUTOMATIC"
	ForecastComputationSeasonality_CUSTOM    ForecastComputationSeasonality = "CUSTOM"
)

type FunnelChartMeasureDataLabelStyle string

const (
	FunnelChartMeasureDataLabelStyle_PERCENTAGE_BY_FIRST_STAGE              FunnelChartMeasureDataLabelStyle = "PERCENTAGE_BY_FIRST_STAGE"
	FunnelChartMeasureDataLabelStyle_PERCENTAGE_BY_PREVIOUS_STAGE           FunnelChartMeasureDataLabelStyle = "PERCENTAGE_BY_PREVIOUS_STAGE"
	FunnelChartMeasureDataLabelStyle_VALUE_AND_PERCENTAGE_BY_FIRST_STAGE    FunnelChartMeasureDataLabelStyle = "VALUE_AND_PERCENTAGE_BY_FIRST_STAGE"
	FunnelChartMeasureDataLabelStyle_VALUE_AND_PERCENTAGE_BY_PREVIOUS_STAGE FunnelChartMeasureDataLabelStyle = "VALUE_AND_PERCENTAGE_BY_PREVIOUS_STAGE"
	FunnelChartMeasureDataLabelStyle_VALUE_ONLY                             FunnelChartMeasureDataLabelStyle = "VALUE_ONLY"
)

type GeneratedAnswerStatus string

const (
	GeneratedAnswerStatus_ANSWER_DOWNGRADE GeneratedAnswerStatus = "ANSWER_DOWNGRADE"
	GeneratedAnswerStatus_ANSWER_GENERATED GeneratedAnswerStatus = "ANSWER_GENERATED"
	GeneratedAnswerStatus_ANSWER_RETRIEVED GeneratedAnswerStatus = "ANSWER_RETRIEVED"
)

type GeoSpatialCountryCode string

const (
	GeoSpatialCountryCode_US GeoSpatialCountryCode = "US"
)

type GeoSpatialDataRole string

const (
	GeoSpatialDataRole_CITY      GeoSpatialDataRole = "CITY"
	GeoSpatialDataRole_COUNTRY   GeoSpatialDataRole = "COUNTRY"
	GeoSpatialDataRole_COUNTY    GeoSpatialDataRole = "COUNTY"
	GeoSpatialDataRole_LATITUDE  GeoSpatialDataRole = "LATITUDE"
	GeoSpatialDataRole_LONGITUDE GeoSpatialDataRole = "LONGITUDE"
	GeoSpatialDataRole_POSTCODE  GeoSpatialDataRole = "POSTCODE"
	GeoSpatialDataRole_STATE     GeoSpatialDataRole = "STATE"
)

type GeospatialColorState string

const (
	GeospatialColorState_DISABLED GeospatialColorState = "DISABLED"
	GeospatialColorState_ENABLED  GeospatialColorState = "ENABLED"
)

type GeospatialLayerType string

const (
	GeospatialLayerType_LINE    GeospatialLayerType = "LINE"
	GeospatialLayerType_POINT   GeospatialLayerType = "POINT"
	GeospatialLayerType_POLYGON GeospatialLayerType = "POLYGON"
)

type GeospatialMapNavigation string

const (
	GeospatialMapNavigation_DISABLED GeospatialMapNavigation = "DISABLED"
	GeospatialMapNavigation_ENABLED  GeospatialMapNavigation = "ENABLED"
)

type GeospatialSelectedPointStyle string

const (
	GeospatialSelectedPointStyle_CLUSTER GeospatialSelectedPointStyle = "CLUSTER"
	GeospatialSelectedPointStyle_HEATMAP GeospatialSelectedPointStyle = "HEATMAP"
	GeospatialSelectedPointStyle_POINT   GeospatialSelectedPointStyle = "POINT"
)

type GroupFilterAttribute string

const (
	GroupFilterAttribute_GROUP_NAME GroupFilterAttribute = "GROUP_NAME"
)

type GroupFilterOperator string

const (
	GroupFilterOperator_StartsWith GroupFilterOperator = "StartsWith"
)

type HistogramBinType string

const (
	HistogramBinType_BIN_COUNT HistogramBinType = "BIN_COUNT"
	HistogramBinType_BIN_WIDTH HistogramBinType = "BIN_WIDTH"
)

type HorizontalTextAlignment string

const (
	HorizontalTextAlignment_AUTO   HorizontalTextAlignment = "AUTO"
	HorizontalTextAlignment_CENTER HorizontalTextAlignment = "CENTER"
	HorizontalTextAlignment_LEFT   HorizontalTextAlignment = "LEFT"
	HorizontalTextAlignment_RIGHT  HorizontalTextAlignment = "RIGHT"
)

type Icon string

const (
	Icon_ARROW_DOWN       Icon = "ARROW_DOWN"
	Icon_ARROW_DOWN_LEFT  Icon = "ARROW_DOWN_LEFT"
	Icon_ARROW_DOWN_RIGHT Icon = "ARROW_DOWN_RIGHT"
	Icon_ARROW_LEFT       Icon = "ARROW_LEFT"
	Icon_ARROW_RIGHT      Icon = "ARROW_RIGHT"
	Icon_ARROW_UP         Icon = "ARROW_UP"
	Icon_ARROW_UP_LEFT    Icon = "ARROW_UP_LEFT"
	Icon_ARROW_UP_RIGHT   Icon = "ARROW_UP_RIGHT"
	Icon_CARET_DOWN       Icon = "CARET_DOWN"
	Icon_CARET_UP         Icon = "CARET_UP"
	Icon_CHECKMARK        Icon = "CHECKMARK"
	Icon_CIRCLE           Icon = "CIRCLE"
	Icon_FACE_DOWN        Icon = "FACE_DOWN"
	Icon_FACE_FLAT        Icon = "FACE_FLAT"
	Icon_FACE_UP          Icon = "FACE_UP"
	Icon_FLAG             Icon = "FLAG"
	Icon_MINUS            Icon = "MINUS"
	Icon_ONE_BAR          Icon = "ONE_BAR"
	Icon_PLUS             Icon = "PLUS"
	Icon_SQUARE           Icon = "SQUARE"
	Icon_THREE_BAR        Icon = "THREE_BAR"
	Icon_THUMBS_DOWN      Icon = "THUMBS_DOWN"
	Icon_THUMBS_UP        Icon = "THUMBS_UP"
	Icon_TRIANGLE         Icon = "TRIANGLE"
	Icon_TWO_BAR          Icon = "TWO_BAR"
	Icon_X                Icon = "X"
)

type IdentityStore string

const (
	IdentityStore_QUICKSIGHT IdentityStore = "QUICKSIGHT"
)

type IdentityType string

const (
	IdentityType_IAM                 IdentityType = "IAM"
	IdentityType_IAM_IDENTITY_CENTER IdentityType = "IAM_IDENTITY_CENTER"
	IdentityType_QUICKSIGHT          IdentityType = "QUICKSIGHT"
)

type ImageCustomActionTrigger string

const (
	ImageCustomActionTrigger_CLICK ImageCustomActionTrigger = "CLICK"
	ImageCustomActionTrigger_MENU  ImageCustomActionTrigger = "MENU"
)

type IncludeFolderMembers string

const (
	IncludeFolderMembers_NONE      IncludeFolderMembers = "NONE"
	IncludeFolderMembers_ONE_LEVEL IncludeFolderMembers = "ONE_LEVEL"
	IncludeFolderMembers_RECURSE   IncludeFolderMembers = "RECURSE"
)

type IncludeGeneratedAnswer string

const (
	IncludeGeneratedAnswer_EXCLUDE IncludeGeneratedAnswer = "EXCLUDE"
	IncludeGeneratedAnswer_INCLUDE IncludeGeneratedAnswer = "INCLUDE"
)

type IncludeQuickSightQIndex string

const (
	IncludeQuickSightQIndex_EXCLUDE IncludeQuickSightQIndex = "EXCLUDE"
	IncludeQuickSightQIndex_INCLUDE IncludeQuickSightQIndex = "INCLUDE"
)

type IngestionErrorType string

const (
	IngestionErrorType_ACCOUNT_CAPACITY_LIMIT_EXCEEDED    IngestionErrorType = "ACCOUNT_CAPACITY_LIMIT_EXCEEDED"
	IngestionErrorType_CONNECTION_FAILURE                 IngestionErrorType = "CONNECTION_FAILURE"
	IngestionErrorType_CURSOR_NOT_ENABLED                 IngestionErrorType = "CURSOR_NOT_ENABLED"
	IngestionErrorType_CUSTOMER_ERROR                     IngestionErrorType = "CUSTOMER_ERROR"
	IngestionErrorType_DATA_SET_DELETED                   IngestionErrorType = "DATA_SET_DELETED"
	IngestionErrorType_DATA_SET_NOT_SPICE                 IngestionErrorType = "DATA_SET_NOT_SPICE"
	IngestionErrorType_DATA_SET_SIZE_LIMIT_EXCEEDED       IngestionErrorType = "DATA_SET_SIZE_LIMIT_EXCEEDED"
	IngestionErrorType_DATA_SOURCE_AUTH_FAILED            IngestionErrorType = "DATA_SOURCE_AUTH_FAILED"
	IngestionErrorType_DATA_SOURCE_CONNECTION_FAILED      IngestionErrorType = "DATA_SOURCE_CONNECTION_FAILED"
	IngestionErrorType_DATA_SOURCE_NOT_FOUND              IngestionErrorType = "DATA_SOURCE_NOT_FOUND"
	IngestionErrorType_DATA_TOLERANCE_EXCEPTION           IngestionErrorType = "DATA_TOLERANCE_EXCEPTION"
	IngestionErrorType_DUPLICATE_COLUMN_NAMES_FOUND       IngestionErrorType = "DUPLICATE_COLUMN_NAMES_FOUND"
	IngestionErrorType_ELASTICSEARCH_CURSOR_NOT_ENABLED   IngestionErrorType = "ELASTICSEARCH_CURSOR_NOT_ENABLED"
	IngestionErrorType_FAILURE_TO_ASSUME_ROLE             IngestionErrorType = "FAILURE_TO_ASSUME_ROLE"
	IngestionErrorType_FAILURE_TO_PROCESS_JSON_FILE       IngestionErrorType = "FAILURE_TO_PROCESS_JSON_FILE"
	IngestionErrorType_IAM_ROLE_NOT_AVAILABLE             IngestionErrorType = "IAM_ROLE_NOT_AVAILABLE"
	IngestionErrorType_INGESTION_CANCELED                 IngestionErrorType = "INGESTION_CANCELED"
	IngestionErrorType_INGESTION_SUPERSEDED               IngestionErrorType = "INGESTION_SUPERSEDED"
	IngestionErrorType_INTERNAL_SERVICE_ERROR             IngestionErrorType = "INTERNAL_SERVICE_ERROR"
	IngestionErrorType_INVALID_DATAPREP_SYNTAX            IngestionErrorType = "INVALID_DATAPREP_SYNTAX"
	IngestionErrorType_INVALID_DATA_SOURCE_CONFIG         IngestionErrorType = "INVALID_DATA_SOURCE_CONFIG"
	IngestionErrorType_INVALID_DATE_FORMAT                IngestionErrorType = "INVALID_DATE_FORMAT"
	IngestionErrorType_IOT_DATA_SET_FILE_EMPTY            IngestionErrorType = "IOT_DATA_SET_FILE_EMPTY"
	IngestionErrorType_IOT_FILE_NOT_FOUND                 IngestionErrorType = "IOT_FILE_NOT_FOUND"
	IngestionErrorType_OAUTH_TOKEN_FAILURE                IngestionErrorType = "OAUTH_TOKEN_FAILURE"
	IngestionErrorType_PASSWORD_AUTHENTICATION_FAILURE    IngestionErrorType = "PASSWORD_AUTHENTICATION_FAILURE"
	IngestionErrorType_PERMISSION_DENIED                  IngestionErrorType = "PERMISSION_DENIED"
	IngestionErrorType_PERMISSION_NOT_FOUND               IngestionErrorType = "PERMISSION_NOT_FOUND"
	IngestionErrorType_QUERY_TIMEOUT                      IngestionErrorType = "QUERY_TIMEOUT"
	IngestionErrorType_REFRESH_SUPPRESSED_BY_EDIT         IngestionErrorType = "REFRESH_SUPPRESSED_BY_EDIT"
	IngestionErrorType_ROW_SIZE_LIMIT_EXCEEDED            IngestionErrorType = "ROW_SIZE_LIMIT_EXCEEDED"
	IngestionErrorType_S3_FILE_INACCESSIBLE               IngestionErrorType = "S3_FILE_INACCESSIBLE"
	IngestionErrorType_S3_MANIFEST_ERROR                  IngestionErrorType = "S3_MANIFEST_ERROR"
	IngestionErrorType_S3_UPLOADED_FILE_DELETED           IngestionErrorType = "S3_UPLOADED_FILE_DELETED"
	IngestionErrorType_SOURCE_API_LIMIT_EXCEEDED_FAILURE  IngestionErrorType = "SOURCE_API_LIMIT_EXCEEDED_FAILURE"
	IngestionErrorType_SOURCE_RESOURCE_LIMIT_EXCEEDED     IngestionErrorType = "SOURCE_RESOURCE_LIMIT_EXCEEDED"
	IngestionErrorType_SPICE_TABLE_NOT_FOUND              IngestionErrorType = "SPICE_TABLE_NOT_FOUND"
	IngestionErrorType_SQL_EXCEPTION                      IngestionErrorType = "SQL_EXCEPTION"
	IngestionErrorType_SQL_INVALID_PARAMETER_VALUE        IngestionErrorType = "SQL_INVALID_PARAMETER_VALUE"
	IngestionErrorType_SQL_NUMERIC_OVERFLOW               IngestionErrorType = "SQL_NUMERIC_OVERFLOW"
	IngestionErrorType_SQL_SCHEMA_MISMATCH_ERROR          IngestionErrorType = "SQL_SCHEMA_MISMATCH_ERROR"
	IngestionErrorType_SQL_TABLE_NOT_FOUND                IngestionErrorType = "SQL_TABLE_NOT_FOUND"
	IngestionErrorType_SSL_CERTIFICATE_VALIDATION_FAILURE IngestionErrorType = "SSL_CERTIFICATE_VALIDATION_FAILURE"
	IngestionErrorType_UNRESOLVABLE_HOST                  IngestionErrorType = "UNRESOLVABLE_HOST"
	IngestionErrorType_UNROUTABLE_HOST                    IngestionErrorType = "UNROUTABLE_HOST"
)

type IngestionRequestSource string

const (
	IngestionRequestSource_MANUAL    IngestionRequestSource = "MANUAL"
	IngestionRequestSource_SCHEDULED IngestionRequestSource = "SCHEDULED"
)

type IngestionRequestType string

const (
	IngestionRequestType_EDIT                IngestionRequestType = "EDIT"
	IngestionRequestType_FULL_REFRESH        IngestionRequestType = "FULL_REFRESH"
	IngestionRequestType_INCREMENTAL_REFRESH IngestionRequestType = "INCREMENTAL_REFRESH"
	IngestionRequestType_INITIAL_INGESTION   IngestionRequestType = "INITIAL_INGESTION"
)

type IngestionStatus string

const (
	IngestionStatus_CANCELLED   IngestionStatus = "CANCELLED"
	IngestionStatus_COMPLETED   IngestionStatus = "COMPLETED"
	IngestionStatus_FAILED      IngestionStatus = "FAILED"
	IngestionStatus_INITIALIZED IngestionStatus = "INITIALIZED"
	IngestionStatus_QUEUED      IngestionStatus = "QUEUED"
	IngestionStatus_RUNNING     IngestionStatus = "RUNNING"
)

type IngestionType string

const (
	IngestionType_FULL_REFRESH        IngestionType = "FULL_REFRESH"
	IngestionType_INCREMENTAL_REFRESH IngestionType = "INCREMENTAL_REFRESH"
)

type InputColumnDataType string

const (
	InputColumnDataType_BIT      InputColumnDataType = "BIT"
	InputColumnDataType_BOOLEAN  InputColumnDataType = "BOOLEAN"
	InputColumnDataType_DATETIME InputColumnDataType = "DATETIME"
	InputColumnDataType_DECIMAL  InputColumnDataType = "DECIMAL"
	InputColumnDataType_INTEGER  InputColumnDataType = "INTEGER"
	InputColumnDataType_JSON     InputColumnDataType = "JSON"
	InputColumnDataType_STRING   InputColumnDataType = "STRING"
)

type JoinOperationType string

const (
	JoinOperationType_INNER JoinOperationType = "INNER"
	JoinOperationType_LEFT  JoinOperationType = "LEFT"
	JoinOperationType_OUTER JoinOperationType = "OUTER"
	JoinOperationType_RIGHT JoinOperationType = "RIGHT"
)

type JoinType string

const (
	JoinType_INNER JoinType = "INNER"
	JoinType_LEFT  JoinType = "LEFT"
	JoinType_OUTER JoinType = "OUTER"
	JoinType_RIGHT JoinType = "RIGHT"
)

type KPISparklineType string

const (
	KPISparklineType_AREA KPISparklineType = "AREA"
	KPISparklineType_LINE KPISparklineType = "LINE"
)

type KPIVisualStandardLayoutType string

const (
	KPIVisualStandardLayoutType_CLASSIC  KPIVisualStandardLayoutType = "CLASSIC"
	KPIVisualStandardLayoutType_VERTICAL KPIVisualStandardLayoutType = "VERTICAL"
)

type LayerCustomActionTrigger string

const (
	LayerCustomActionTrigger_DATA_POINT_CLICK LayerCustomActionTrigger = "DATA_POINT_CLICK"
	LayerCustomActionTrigger_DATA_POINT_MENU  LayerCustomActionTrigger = "DATA_POINT_MENU"
)

type LayoutElementType string

const (
	LayoutElementType_FILTER_CONTROL    LayoutElementType = "FILTER_CONTROL"
	LayoutElementType_IMAGE             LayoutElementType = "IMAGE"
	LayoutElementType_PARAMETER_CONTROL LayoutElementType = "PARAMETER_CONTROL"
	LayoutElementType_TEXT_BOX          LayoutElementType = "TEXT_BOX"
	LayoutElementType_VISUAL            LayoutElementType = "VISUAL"
)

type LegendPosition string

const (
	LegendPosition_AUTO   LegendPosition = "AUTO"
	LegendPosition_BOTTOM LegendPosition = "BOTTOM"
	LegendPosition_RIGHT  LegendPosition = "RIGHT"
	LegendPosition_TOP    LegendPosition = "TOP"
)

type LineChartLineStyle string

const (
	LineChartLineStyle_DASHED LineChartLineStyle = "DASHED"
	LineChartLineStyle_DOTTED LineChartLineStyle = "DOTTED"
	LineChartLineStyle_SOLID  LineChartLineStyle = "SOLID"
)

type LineChartMarkerShape string

const (
	LineChartMarkerShape_CIRCLE         LineChartMarkerShape = "CIRCLE"
	LineChartMarkerShape_DIAMOND        LineChartMarkerShape = "DIAMOND"
	LineChartMarkerShape_ROUNDED_SQUARE LineChartMarkerShape = "ROUNDED_SQUARE"
	LineChartMarkerShape_SQUARE         LineChartMarkerShape = "SQUARE"
	LineChartMarkerShape_TRIANGLE       LineChartMarkerShape = "TRIANGLE"
)

type LineChartType string

const (
	LineChartType_AREA         LineChartType = "AREA"
	LineChartType_LINE         LineChartType = "LINE"
	LineChartType_STACKED_AREA LineChartType = "STACKED_AREA"
)

type LineInterpolation string

const (
	LineInterpolation_LINEAR  LineInterpolation = "LINEAR"
	LineInterpolation_SMOOTH  LineInterpolation = "SMOOTH"
	LineInterpolation_STEPPED LineInterpolation = "STEPPED"
)

type LookbackWindowSizeUnit string

const (
	LookbackWindowSizeUnit_DAY  LookbackWindowSizeUnit = "DAY"
	LookbackWindowSizeUnit_HOUR LookbackWindowSizeUnit = "HOUR"
	LookbackWindowSizeUnit_WEEK LookbackWindowSizeUnit = "WEEK"
)

type MapZoomMode string

const (
	MapZoomMode_AUTO   MapZoomMode = "AUTO"
	MapZoomMode_MANUAL MapZoomMode = "MANUAL"
)

type MaximumMinimumComputationType string

const (
	MaximumMinimumComputationType_MAXIMUM MaximumMinimumComputationType = "MAXIMUM"
	MaximumMinimumComputationType_MINIMUM MaximumMinimumComputationType = "MINIMUM"
)

type MemberType string

const (
	MemberType_ANALYSIS   MemberType = "ANALYSIS"
	MemberType_DASHBOARD  MemberType = "DASHBOARD"
	MemberType_DATASET    MemberType = "DATASET"
	MemberType_DATASOURCE MemberType = "DATASOURCE"
	MemberType_TOPIC      MemberType = "TOPIC"
)

type MissingDataTreatmentOption string

const (
	MissingDataTreatmentOption_INTERPOLATE   MissingDataTreatmentOption = "INTERPOLATE"
	MissingDataTreatmentOption_SHOW_AS_BLANK MissingDataTreatmentOption = "SHOW_AS_BLANK"
	MissingDataTreatmentOption_SHOW_AS_ZERO  MissingDataTreatmentOption = "SHOW_AS_ZERO"
)

type NamedEntityAggType string

const (
	NamedEntityAggType_AVERAGE        NamedEntityAggType = "AVERAGE"
	NamedEntityAggType_COUNT          NamedEntityAggType = "COUNT"
	NamedEntityAggType_CUSTOM         NamedEntityAggType = "CUSTOM"
	NamedEntityAggType_DISTINCT_COUNT NamedEntityAggType = "DISTINCT_COUNT"
	NamedEntityAggType_MAX            NamedEntityAggType = "MAX"
	NamedEntityAggType_MEDIAN         NamedEntityAggType = "MEDIAN"
	NamedEntityAggType_MIN            NamedEntityAggType = "MIN"
	NamedEntityAggType_PERCENTILE     NamedEntityAggType = "PERCENTILE"
	NamedEntityAggType_STDEV          NamedEntityAggType = "STDEV"
	NamedEntityAggType_STDEVP         NamedEntityAggType = "STDEVP"
	NamedEntityAggType_SUM            NamedEntityAggType = "SUM"
	NamedEntityAggType_VAR            NamedEntityAggType = "VAR"
	NamedEntityAggType_VARP           NamedEntityAggType = "VARP"
)

type NamedFilterAggType string

const (
	NamedFilterAggType_AVERAGE        NamedFilterAggType = "AVERAGE"
	NamedFilterAggType_COUNT          NamedFilterAggType = "COUNT"
	NamedFilterAggType_DISTINCT_COUNT NamedFilterAggType = "DISTINCT_COUNT"
	NamedFilterAggType_MAX            NamedFilterAggType = "MAX"
	NamedFilterAggType_MEDIAN         NamedFilterAggType = "MEDIAN"
	NamedFilterAggType_MIN            NamedFilterAggType = "MIN"
	NamedFilterAggType_NO_AGGREGATION NamedFilterAggType = "NO_AGGREGATION"
	NamedFilterAggType_STDEV          NamedFilterAggType = "STDEV"
	NamedFilterAggType_STDEVP         NamedFilterAggType = "STDEVP"
	NamedFilterAggType_SUM            NamedFilterAggType = "SUM"
	NamedFilterAggType_VAR            NamedFilterAggType = "VAR"
	NamedFilterAggType_VARP           NamedFilterAggType = "VARP"
)

type NamedFilterType string

const (
	NamedFilterType_CATEGORY_FILTER         NamedFilterType = "CATEGORY_FILTER"
	NamedFilterType_DATE_RANGE_FILTER       NamedFilterType = "DATE_RANGE_FILTER"
	NamedFilterType_NULL_FILTER             NamedFilterType = "NULL_FILTER"
	NamedFilterType_NUMERIC_EQUALITY_FILTER NamedFilterType = "NUMERIC_EQUALITY_FILTER"
	NamedFilterType_NUMERIC_RANGE_FILTER    NamedFilterType = "NUMERIC_RANGE_FILTER"
	NamedFilterType_RELATIVE_DATE_FILTER    NamedFilterType = "RELATIVE_DATE_FILTER"
)

type NamespaceErrorType string

const (
	NamespaceErrorType_INTERNAL_SERVICE_ERROR NamespaceErrorType = "INTERNAL_SERVICE_ERROR"
	NamespaceErrorType_PERMISSION_DENIED      NamespaceErrorType = "PERMISSION_DENIED"
)

type NamespaceStatus string

const (
	NamespaceStatus_CREATED               NamespaceStatus = "CREATED"
	NamespaceStatus_CREATING              NamespaceStatus = "CREATING"
	NamespaceStatus_DELETING              NamespaceStatus = "DELETING"
	NamespaceStatus_NON_RETRYABLE_FAILURE NamespaceStatus = "NON_RETRYABLE_FAILURE"
	NamespaceStatus_RETRYABLE_FAILURE     NamespaceStatus = "RETRYABLE_FAILURE"
)

type NegativeValueDisplayMode string

const (
	NegativeValueDisplayMode_NEGATIVE NegativeValueDisplayMode = "NEGATIVE"
	NegativeValueDisplayMode_POSITIVE NegativeValueDisplayMode = "POSITIVE"
)

type NetworkInterfaceStatus string

const (
	NetworkInterfaceStatus_ATTACHMENT_FAILED_ROLLBACK_FAILED NetworkInterfaceStatus = "ATTACHMENT_FAILED_ROLLBACK_FAILED"
	NetworkInterfaceStatus_AVAILABLE                         NetworkInterfaceStatus = "AVAILABLE"
	NetworkInterfaceStatus_CREATING                          NetworkInterfaceStatus = "CREATING"
	NetworkInterfaceStatus_CREATION_FAILED                   NetworkInterfaceStatus = "CREATION_FAILED"
	NetworkInterfaceStatus_DELETED                           NetworkInterfaceStatus = "DELETED"
	NetworkInterfaceStatus_DELETING                          NetworkInterfaceStatus = "DELETING"
	NetworkInterfaceStatus_DELETION_FAILED                   NetworkInterfaceStatus = "DELETION_FAILED"
	NetworkInterfaceStatus_DELETION_SCHEDULED                NetworkInterfaceStatus = "DELETION_SCHEDULED"
	NetworkInterfaceStatus_UPDATE_FAILED                     NetworkInterfaceStatus = "UPDATE_FAILED"
	NetworkInterfaceStatus_UPDATING                          NetworkInterfaceStatus = "UPDATING"
)

type NullFilterOption string

const (
	NullFilterOption_ALL_VALUES     NullFilterOption = "ALL_VALUES"
	NullFilterOption_NON_NULLS_ONLY NullFilterOption = "NON_NULLS_ONLY"
	NullFilterOption_NULLS_ONLY     NullFilterOption = "NULLS_ONLY"
)

type NullFilterType string

const (
	NullFilterType_ALL_VALUES     NullFilterType = "ALL_VALUES"
	NullFilterType_NON_NULLS_ONLY NullFilterType = "NON_NULLS_ONLY"
	NullFilterType_NULLS_ONLY     NullFilterType = "NULLS_ONLY"
)

type NumberScale string

const (
	NumberScale_AUTO      NumberScale = "AUTO"
	NumberScale_BILLIONS  NumberScale = "BILLIONS"
	NumberScale_CRORES    NumberScale = "CRORES"
	NumberScale_LAKHS     NumberScale = "LAKHS"
	NumberScale_MILLIONS  NumberScale = "MILLIONS"
	NumberScale_NONE      NumberScale = "NONE"
	NumberScale_THOUSANDS NumberScale = "THOUSANDS"
	NumberScale_TRILLIONS NumberScale = "TRILLIONS"
)

type NumericEqualityMatchOperator string

const (
	NumericEqualityMatchOperator_DOES_NOT_EQUAL NumericEqualityMatchOperator = "DOES_NOT_EQUAL"
	NumericEqualityMatchOperator_EQUALS         NumericEqualityMatchOperator = "EQUALS"
)

type NumericFilterSelectAllOptions string

const (
	NumericFilterSelectAllOptions_FILTER_ALL_VALUES NumericFilterSelectAllOptions = "FILTER_ALL_VALUES"
)

type NumericSeparatorSymbol string

const (
	NumericSeparatorSymbol_COMMA NumericSeparatorSymbol = "COMMA"
	NumericSeparatorSymbol_DOT   NumericSeparatorSymbol = "DOT"
	NumericSeparatorSymbol_SPACE NumericSeparatorSymbol = "SPACE"
)

type OtherCategories string

const (
	OtherCategories_EXCLUDE OtherCategories = "EXCLUDE"
	OtherCategories_INCLUDE OtherCategories = "INCLUDE"
)

type PanelBorderStyle string

const (
	PanelBorderStyle_DASHED PanelBorderStyle = "DASHED"
	PanelBorderStyle_DOTTED PanelBorderStyle = "DOTTED"
	PanelBorderStyle_SOLID  PanelBorderStyle = "SOLID"
)

type PaperOrientation string

const (
	PaperOrientation_LANDSCAPE PaperOrientation = "LANDSCAPE"
	PaperOrientation_PORTRAIT  PaperOrientation = "PORTRAIT"
)

type PaperSize string

const (
	PaperSize_A0                PaperSize = "A0"
	PaperSize_A1                PaperSize = "A1"
	PaperSize_A2                PaperSize = "A2"
	PaperSize_A3                PaperSize = "A3"
	PaperSize_A4                PaperSize = "A4"
	PaperSize_A5                PaperSize = "A5"
	PaperSize_JIS_B4            PaperSize = "JIS_B4"
	PaperSize_JIS_B5            PaperSize = "JIS_B5"
	PaperSize_US_LEGAL          PaperSize = "US_LEGAL"
	PaperSize_US_LETTER         PaperSize = "US_LETTER"
	PaperSize_US_TABLOID_LEDGER PaperSize = "US_TABLOID_LEDGER"
)

type ParameterValueType string

const (
	ParameterValueType_MULTI_VALUED  ParameterValueType = "MULTI_VALUED"
	ParameterValueType_SINGLE_VALUED ParameterValueType = "SINGLE_VALUED"
)

type PersonalizationMode string

const (
	PersonalizationMode_DISABLED PersonalizationMode = "DISABLED"
	PersonalizationMode_ENABLED  PersonalizationMode = "ENABLED"
)

type PivotTableConditionalFormattingScopeRole string

const (
	PivotTableConditionalFormattingScopeRole_FIELD       PivotTableConditionalFormattingScopeRole = "FIELD"
	PivotTableConditionalFormattingScopeRole_FIELD_TOTAL PivotTableConditionalFormattingScopeRole = "FIELD_TOTAL"
	PivotTableConditionalFormattingScopeRole_GRAND_TOTAL PivotTableConditionalFormattingScopeRole = "GRAND_TOTAL"
)

type PivotTableDataPathType string

const (
	PivotTableDataPathType_COUNT_METRIC_COLUMN          PivotTableDataPathType = "COUNT_METRIC_COLUMN"
	PivotTableDataPathType_EMPTY_COLUMN_HEADER          PivotTableDataPathType = "EMPTY_COLUMN_HEADER"
	PivotTableDataPathType_HIERARCHY_ROWS_LAYOUT_COLUMN PivotTableDataPathType = "HIERARCHY_ROWS_LAYOUT_COLUMN"
	PivotTableDataPathType_MULTIPLE_ROW_METRICS_COLUMN  PivotTableDataPathType = "MULTIPLE_ROW_METRICS_COLUMN"
)

type PivotTableFieldCollapseState string

const (
	PivotTableFieldCollapseState_COLLAPSED PivotTableFieldCollapseState = "COLLAPSED"
	PivotTableFieldCollapseState_EXPANDED  PivotTableFieldCollapseState = "EXPANDED"
)

type PivotTableMetricPlacement string

const (
	PivotTableMetricPlacement_COLUMN PivotTableMetricPlacement = "COLUMN"
	PivotTableMetricPlacement_ROW    PivotTableMetricPlacement = "ROW"
)

type PivotTableRowsLayout string

const (
	PivotTableRowsLayout_HIERARCHY PivotTableRowsLayout = "HIERARCHY"
	PivotTableRowsLayout_TABULAR   PivotTableRowsLayout = "TABULAR"
)

type PivotTableSubtotalLevel string

const (
	PivotTableSubtotalLevel_ALL    PivotTableSubtotalLevel = "ALL"
	PivotTableSubtotalLevel_CUSTOM PivotTableSubtotalLevel = "CUSTOM"
	PivotTableSubtotalLevel_LAST   PivotTableSubtotalLevel = "LAST"
)

type PluginVisualAxisName string

const (
	PluginVisualAxisName_GROUP_BY PluginVisualAxisName = "GROUP_BY"
	PluginVisualAxisName_VALUE    PluginVisualAxisName = "VALUE"
)

type PrimaryValueDisplayType string

const (
	PrimaryValueDisplayType_ACTUAL     PrimaryValueDisplayType = "ACTUAL"
	PrimaryValueDisplayType_COMPARISON PrimaryValueDisplayType = "COMPARISON"
	PrimaryValueDisplayType_HIDDEN     PrimaryValueDisplayType = "HIDDEN"
)

type PropertyRole string

const (
	PropertyRole_ID      PropertyRole = "ID"
	PropertyRole_PRIMARY PropertyRole = "PRIMARY"
)

type PropertyUsage string

const (
	PropertyUsage_DIMENSION PropertyUsage = "DIMENSION"
	PropertyUsage_INHERIT   PropertyUsage = "INHERIT"
	PropertyUsage_MEASURE   PropertyUsage = "MEASURE"
)

type PurchaseMode string

const (
	PurchaseMode_AUTO_PURCHASE PurchaseMode = "AUTO_PURCHASE"
	PurchaseMode_MANUAL        PurchaseMode = "MANUAL"
)

type QAResultType string

const (
	QAResultType_DASHBOARD_VISUAL QAResultType = "DASHBOARD_VISUAL"
	QAResultType_GENERATED_ANSWER QAResultType = "GENERATED_ANSWER"
	QAResultType_NO_ANSWER        QAResultType = "NO_ANSWER"
)

type QBusinessInsightsStatus string

const (
	QBusinessInsightsStatus_DISABLED QBusinessInsightsStatus = "DISABLED"
	QBusinessInsightsStatus_ENABLED  QBusinessInsightsStatus = "ENABLED"
)

type QDataKeyType string

const (
	QDataKeyType_AWS_OWNED QDataKeyType = "AWS_OWNED"
	QDataKeyType_CMK       QDataKeyType = "CMK"
)

type QSearchStatus string

const (
	QSearchStatus_DISABLED QSearchStatus = "DISABLED"
	QSearchStatus_ENABLED  QSearchStatus = "ENABLED"
)

type QueryExecutionMode string

const (
	QueryExecutionMode_AUTO   QueryExecutionMode = "AUTO"
	QueryExecutionMode_MANUAL QueryExecutionMode = "MANUAL"
)

type RadarChartAxesRangeScale string

const (
	RadarChartAxesRangeScale_AUTO        RadarChartAxesRangeScale = "AUTO"
	RadarChartAxesRangeScale_INDEPENDENT RadarChartAxesRangeScale = "INDEPENDENT"
	RadarChartAxesRangeScale_SHARED      RadarChartAxesRangeScale = "SHARED"
)

type RadarChartShape string

const (
	RadarChartShape_CIRCLE  RadarChartShape = "CIRCLE"
	RadarChartShape_POLYGON RadarChartShape = "POLYGON"
)

type ReferenceLineLabelHorizontalPosition string

const (
	ReferenceLineLabelHorizontalPosition_CENTER ReferenceLineLabelHorizontalPosition = "CENTER"
	ReferenceLineLabelHorizontalPosition_LEFT   ReferenceLineLabelHorizontalPosition = "LEFT"
	ReferenceLineLabelHorizontalPosition_RIGHT  ReferenceLineLabelHorizontalPosition = "RIGHT"
)

type ReferenceLineLabelVerticalPosition string

const (
	ReferenceLineLabelVerticalPosition_ABOVE ReferenceLineLabelVerticalPosition = "ABOVE"
	ReferenceLineLabelVerticalPosition_BELOW ReferenceLineLabelVerticalPosition = "BELOW"
)

type ReferenceLinePatternType string

const (
	ReferenceLinePatternType_DASHED ReferenceLinePatternType = "DASHED"
	ReferenceLinePatternType_DOTTED ReferenceLinePatternType = "DOTTED"
	ReferenceLinePatternType_SOLID  ReferenceLinePatternType = "SOLID"
)

type ReferenceLineSeriesType string

const (
	ReferenceLineSeriesType_BAR  ReferenceLineSeriesType = "BAR"
	ReferenceLineSeriesType_LINE ReferenceLineSeriesType = "LINE"
)

type ReferenceLineValueLabelRelativePosition string

const (
	ReferenceLineValueLabelRelativePosition_AFTER_CUSTOM_LABEL  ReferenceLineValueLabelRelativePosition = "AFTER_CUSTOM_LABEL"
	ReferenceLineValueLabelRelativePosition_BEFORE_CUSTOM_LABEL ReferenceLineValueLabelRelativePosition = "BEFORE_CUSTOM_LABEL"
)

type RefreshFailureAlertStatus string

const (
	RefreshFailureAlertStatus_DISABLED RefreshFailureAlertStatus = "DISABLED"
	RefreshFailureAlertStatus_ENABLED  RefreshFailureAlertStatus = "ENABLED"
)

type RefreshInterval string

const (
	RefreshInterval_DAILY    RefreshInterval = "DAILY"
	RefreshInterval_HOURLY   RefreshInterval = "HOURLY"
	RefreshInterval_MINUTE15 RefreshInterval = "MINUTE15"
	RefreshInterval_MINUTE30 RefreshInterval = "MINUTE30"
	RefreshInterval_MONTHLY  RefreshInterval = "MONTHLY"
	RefreshInterval_WEEKLY   RefreshInterval = "WEEKLY"
)

type RelativeDateType string

const (
	RelativeDateType_LAST     RelativeDateType = "LAST"
	RelativeDateType_NEXT     RelativeDateType = "NEXT"
	RelativeDateType_NOW      RelativeDateType = "NOW"
	RelativeDateType_PREVIOUS RelativeDateType = "PREVIOUS"
	RelativeDateType_THIS     RelativeDateType = "THIS"
)

type RelativeFontSize string

const (
	RelativeFontSize_EXTRA_LARGE RelativeFontSize = "EXTRA_LARGE"
	RelativeFontSize_EXTRA_SMALL RelativeFontSize = "EXTRA_SMALL"
	RelativeFontSize_LARGE       RelativeFontSize = "LARGE"
	RelativeFontSize_MEDIUM      RelativeFontSize = "MEDIUM"
	RelativeFontSize_SMALL       RelativeFontSize = "SMALL"
)

type ResizeOption string

const (
	ResizeOption_FIXED      ResizeOption = "FIXED"
	ResizeOption_RESPONSIVE ResizeOption = "RESPONSIVE"
)

type ResourceStatus string

const (
	ResourceStatus_CREATION_FAILED      ResourceStatus = "CREATION_FAILED"
	ResourceStatus_CREATION_IN_PROGRESS ResourceStatus = "CREATION_IN_PROGRESS"
	ResourceStatus_CREATION_SUCCESSFUL  ResourceStatus = "CREATION_SUCCESSFUL"
	ResourceStatus_DELETED              ResourceStatus = "DELETED"
	ResourceStatus_UPDATE_FAILED        ResourceStatus = "UPDATE_FAILED"
	ResourceStatus_UPDATE_IN_PROGRESS   ResourceStatus = "UPDATE_IN_PROGRESS"
	ResourceStatus_UPDATE_SUCCESSFUL    ResourceStatus = "UPDATE_SUCCESSFUL"
)

type ReviewedAnswerErrorCode string

const (
	ReviewedAnswerErrorCode_DATASET_DOES_NOT_EXIST  ReviewedAnswerErrorCode = "DATASET_DOES_NOT_EXIST"
	ReviewedAnswerErrorCode_DUPLICATED_ANSWER       ReviewedAnswerErrorCode = "DUPLICATED_ANSWER"
	ReviewedAnswerErrorCode_INTERNAL_ERROR          ReviewedAnswerErrorCode = "INTERNAL_ERROR"
	ReviewedAnswerErrorCode_INVALID_DATA            ReviewedAnswerErrorCode = "INVALID_DATA"
	ReviewedAnswerErrorCode_INVALID_DATASET_ARN     ReviewedAnswerErrorCode = "INVALID_DATASET_ARN"
	ReviewedAnswerErrorCode_MISSING_ANSWER          ReviewedAnswerErrorCode = "MISSING_ANSWER"
	ReviewedAnswerErrorCode_MISSING_REQUIRED_FIELDS ReviewedAnswerErrorCode = "MISSING_REQUIRED_FIELDS"
)

type Role string

const (
	Role_ADMIN      Role = "ADMIN"
	Role_ADMIN_PRO  Role = "ADMIN_PRO"
	Role_AUTHOR     Role = "AUTHOR"
	Role_AUTHOR_PRO Role = "AUTHOR_PRO"
	Role_READER     Role = "READER"
	Role_READER_PRO Role = "READER_PRO"
)

type RowLevelPermissionFormatVersion string

const (
	RowLevelPermissionFormatVersion_VERSION_1 RowLevelPermissionFormatVersion = "VERSION_1"
	RowLevelPermissionFormatVersion_VERSION_2 RowLevelPermissionFormatVersion = "VERSION_2"
)

type RowLevelPermissionPolicy string

const (
	RowLevelPermissionPolicy_DENY_ACCESS  RowLevelPermissionPolicy = "DENY_ACCESS"
	RowLevelPermissionPolicy_GRANT_ACCESS RowLevelPermissionPolicy = "GRANT_ACCESS"
)

type SearchFilterOperator string

const (
	SearchFilterOperator_StringEquals SearchFilterOperator = "StringEquals"
	SearchFilterOperator_StringLike   SearchFilterOperator = "StringLike"
)

type SectionPageBreakStatus string

const (
	SectionPageBreakStatus_DISABLED SectionPageBreakStatus = "DISABLED"
	SectionPageBreakStatus_ENABLED  SectionPageBreakStatus = "ENABLED"
)

type SelectAllValueOptions string

const (
	SelectAllValueOptions_ALL_VALUES SelectAllValueOptions = "ALL_VALUES"
)

type SelectedFieldOptions string

const (
	SelectedFieldOptions_ALL_FIELDS SelectedFieldOptions = "ALL_FIELDS"
)

type SelectedTooltipType string

const (
	SelectedTooltipType_BASIC    SelectedTooltipType = "BASIC"
	SelectedTooltipType_DETAILED SelectedTooltipType = "DETAILED"
)

type ServiceType string

const (
	ServiceType_ATHENA    ServiceType = "ATHENA"
	ServiceType_QBUSINESS ServiceType = "QBUSINESS"
	ServiceType_REDSHIFT  ServiceType = "REDSHIFT"
)

type SharingModel string

const (
	SharingModel_ACCOUNT   SharingModel = "ACCOUNT"
	SharingModel_NAMESPACE SharingModel = "NAMESPACE"
)

type SheetContentType string

const (
	SheetContentType_INTERACTIVE SheetContentType = "INTERACTIVE"
	SheetContentType_PAGINATED   SheetContentType = "PAGINATED"
)

type SheetControlDateTimePickerType string

const (
	SheetControlDateTimePickerType_DATE_RANGE    SheetControlDateTimePickerType = "DATE_RANGE"
	SheetControlDateTimePickerType_SINGLE_VALUED SheetControlDateTimePickerType = "SINGLE_VALUED"
)

type SheetControlListType string

const (
	SheetControlListType_MULTI_SELECT  SheetControlListType = "MULTI_SELECT"
	SheetControlListType_SINGLE_SELECT SheetControlListType = "SINGLE_SELECT"
)

type SheetControlSliderType string

const (
	SheetControlSliderType_RANGE        SheetControlSliderType = "RANGE"
	SheetControlSliderType_SINGLE_POINT SheetControlSliderType = "SINGLE_POINT"
)

type SheetImageScalingType string

const (
	SheetImageScalingType_SCALE_NONE         SheetImageScalingType = "SCALE_NONE"
	SheetImageScalingType_SCALE_TO_CONTAINER SheetImageScalingType = "SCALE_TO_CONTAINER"
	SheetImageScalingType_SCALE_TO_HEIGHT    SheetImageScalingType = "SCALE_TO_HEIGHT"
	SheetImageScalingType_SCALE_TO_WIDTH     SheetImageScalingType = "SCALE_TO_WIDTH"
)

type SimpleAttributeAggregationFunction string

const (
	SimpleAttributeAggregationFunction_UNIQUE_VALUE SimpleAttributeAggregationFunction = "UNIQUE_VALUE"
)

type SimpleNumericalAggregationFunction string

const (
	SimpleNumericalAggregationFunction_AVERAGE        SimpleNumericalAggregationFunction = "AVERAGE"
	SimpleNumericalAggregationFunction_COUNT          SimpleNumericalAggregationFunction = "COUNT"
	SimpleNumericalAggregationFunction_DISTINCT_COUNT SimpleNumericalAggregationFunction = "DISTINCT_COUNT"
	SimpleNumericalAggregationFunction_MAX            SimpleNumericalAggregationFunction = "MAX"
	SimpleNumericalAggregationFunction_MEDIAN         SimpleNumericalAggregationFunction = "MEDIAN"
	SimpleNumericalAggregationFunction_MIN            SimpleNumericalAggregationFunction = "MIN"
	SimpleNumericalAggregationFunction_STDEV          SimpleNumericalAggregationFunction = "STDEV"
	SimpleNumericalAggregationFunction_STDEVP         SimpleNumericalAggregationFunction = "STDEVP"
	SimpleNumericalAggregationFunction_SUM            SimpleNumericalAggregationFunction = "SUM"
	SimpleNumericalAggregationFunction_VAR            SimpleNumericalAggregationFunction = "VAR"
	SimpleNumericalAggregationFunction_VARP           SimpleNumericalAggregationFunction = "VARP"
)

type SimpleTotalAggregationFunction string

const (
	SimpleTotalAggregationFunction_AVERAGE SimpleTotalAggregationFunction = "AVERAGE"
	SimpleTotalAggregationFunction_DEFAULT SimpleTotalAggregationFunction = "DEFAULT"
	SimpleTotalAggregationFunction_MAX     SimpleTotalAggregationFunction = "MAX"
	SimpleTotalAggregationFunction_MIN     SimpleTotalAggregationFunction = "MIN"
	SimpleTotalAggregationFunction_NONE    SimpleTotalAggregationFunction = "NONE"
	SimpleTotalAggregationFunction_SUM     SimpleTotalAggregationFunction = "SUM"
)

type SingleYAxisOption string

const (
	SingleYAxisOption_PRIMARY_Y_AXIS SingleYAxisOption = "PRIMARY_Y_AXIS"
)

type SmallMultiplesAxisPlacement string

const (
	SmallMultiplesAxisPlacement_INSIDE  SmallMultiplesAxisPlacement = "INSIDE"
	SmallMultiplesAxisPlacement_OUTSIDE SmallMultiplesAxisPlacement = "OUTSIDE"
)

type SmallMultiplesAxisScale string

const (
	SmallMultiplesAxisScale_INDEPENDENT SmallMultiplesAxisScale = "INDEPENDENT"
	SmallMultiplesAxisScale_SHARED      SmallMultiplesAxisScale = "SHARED"
)

type SnapshotFileFormatType string

const (
	SnapshotFileFormatType_CSV   SnapshotFileFormatType = "CSV"
	SnapshotFileFormatType_EXCEL SnapshotFileFormatType = "EXCEL"
	SnapshotFileFormatType_PDF   SnapshotFileFormatType = "PDF"
)

type SnapshotFileSheetSelectionScope string

const (
	SnapshotFileSheetSelectionScope_ALL_VISUALS      SnapshotFileSheetSelectionScope = "ALL_VISUALS"
	SnapshotFileSheetSelectionScope_SELECTED_VISUALS SnapshotFileSheetSelectionScope = "SELECTED_VISUALS"
)

type SnapshotJobStatus string

const (
	SnapshotJobStatus_COMPLETED SnapshotJobStatus = "COMPLETED"
	SnapshotJobStatus_FAILED    SnapshotJobStatus = "FAILED"
	SnapshotJobStatus_QUEUED    SnapshotJobStatus = "QUEUED"
	SnapshotJobStatus_RUNNING   SnapshotJobStatus = "RUNNING"
)

type SortDirection string

const (
	SortDirection_ASC  SortDirection = "ASC"
	SortDirection_DESC SortDirection = "DESC"
)

type SpecialValue string

const (
	SpecialValue_EMPTY SpecialValue = "EMPTY"
	SpecialValue_NULL  SpecialValue = "NULL"
	SpecialValue_OTHER SpecialValue = "OTHER"
)

type StarburstProductType string

const (
	StarburstProductType_ENTERPRISE StarburstProductType = "ENTERPRISE"
	StarburstProductType_GALAXY     StarburstProductType = "GALAXY"
)

type Status string

const (
	Status_DISABLED Status = "DISABLED"
	Status_ENABLED  Status = "ENABLED"
)

type StyledCellType string

const (
	StyledCellType_METRIC_HEADER StyledCellType = "METRIC_HEADER"
	StyledCellType_TOTAL         StyledCellType = "TOTAL"
	StyledCellType_VALUE         StyledCellType = "VALUE"
)

type TableBorderStyle string

const (
	TableBorderStyle_NONE  TableBorderStyle = "NONE"
	TableBorderStyle_SOLID TableBorderStyle = "SOLID"
)

type TableCellImageScalingConfiguration string

const (
	TableCellImageScalingConfiguration_DO_NOT_SCALE       TableCellImageScalingConfiguration = "DO_NOT_SCALE"
	TableCellImageScalingConfiguration_FIT_TO_CELL_HEIGHT TableCellImageScalingConfiguration = "FIT_TO_CELL_HEIGHT"
	TableCellImageScalingConfiguration_FIT_TO_CELL_WIDTH  TableCellImageScalingConfiguration = "FIT_TO_CELL_WIDTH"
)

type TableFieldIconSetType string

const (
	TableFieldIconSetType_LINK TableFieldIconSetType = "LINK"
)

type TableOrientation string

const (
	TableOrientation_HORIZONTAL TableOrientation = "HORIZONTAL"
	TableOrientation_VERTICAL   TableOrientation = "VERTICAL"
)

type TableTotalsPlacement string

const (
	TableTotalsPlacement_AUTO  TableTotalsPlacement = "AUTO"
	TableTotalsPlacement_END   TableTotalsPlacement = "END"
	TableTotalsPlacement_START TableTotalsPlacement = "START"
)

type TableTotalsScrollStatus string

const (
	TableTotalsScrollStatus_PINNED   TableTotalsScrollStatus = "PINNED"
	TableTotalsScrollStatus_SCROLLED TableTotalsScrollStatus = "SCROLLED"
)

type TargetVisualOptions string

const (
	TargetVisualOptions_ALL_VISUALS TargetVisualOptions = "ALL_VISUALS"
)

type TemplateErrorType string

const (
	TemplateErrorType_ACCESS_DENIED      TemplateErrorType = "ACCESS_DENIED"
	TemplateErrorType_DATA_SET_NOT_FOUND TemplateErrorType = "DATA_SET_NOT_FOUND"
	TemplateErrorType_INTERNAL_FAILURE   TemplateErrorType = "INTERNAL_FAILURE"
	TemplateErrorType_SOURCE_NOT_FOUND   TemplateErrorType = "SOURCE_NOT_FOUND"
)

type TextQualifier string

const (
	TextQualifier_DOUBLE_QUOTE TextQualifier = "DOUBLE_QUOTE"
	TextQualifier_SINGLE_QUOTE TextQualifier = "SINGLE_QUOTE"
)

type TextTransform string

const (
	TextTransform_CAPITALIZE TextTransform = "CAPITALIZE"
)

type TextWrap string

const (
	TextWrap_NONE TextWrap = "NONE"
	TextWrap_WRAP TextWrap = "WRAP"
)

type ThemeErrorType string

const (
	ThemeErrorType_INTERNAL_FAILURE ThemeErrorType = "INTERNAL_FAILURE"
)

type ThemeType string

const (
	ThemeType_ALL        ThemeType = "ALL"
	ThemeType_CUSTOM     ThemeType = "CUSTOM"
	ThemeType_QUICKSIGHT ThemeType = "QUICKSIGHT"
)

type TimeGranularity string

const (
	TimeGranularity_DAY         TimeGranularity = "DAY"
	TimeGranularity_HOUR        TimeGranularity = "HOUR"
	TimeGranularity_MILLISECOND TimeGranularity = "MILLISECOND"
	TimeGranularity_MINUTE      TimeGranularity = "MINUTE"
	TimeGranularity_MONTH       TimeGranularity = "MONTH"
	TimeGranularity_QUARTER     TimeGranularity = "QUARTER"
	TimeGranularity_SECOND      TimeGranularity = "SECOND"
	TimeGranularity_WEEK        TimeGranularity = "WEEK"
	TimeGranularity_YEAR        TimeGranularity = "YEAR"
)

type TooltipTarget string

const (
	TooltipTarget_BAR  TooltipTarget = "BAR"
	TooltipTarget_BOTH TooltipTarget = "BOTH"
	TooltipTarget_LINE TooltipTarget = "LINE"
)

type TooltipTitleType string

const (
	TooltipTitleType_NONE          TooltipTitleType = "NONE"
	TooltipTitleType_PRIMARY_VALUE TooltipTitleType = "PRIMARY_VALUE"
)

type TopBottomComputationType string

const (
	TopBottomComputationType_BOTTOM TopBottomComputationType = "BOTTOM"
	TopBottomComputationType_TOP    TopBottomComputationType = "TOP"
)

type TopBottomSortOrder string

const (
	TopBottomSortOrder_ABSOLUTE_DIFFERENCE TopBottomSortOrder = "ABSOLUTE_DIFFERENCE"
	TopBottomSortOrder_PERCENT_DIFFERENCE  TopBottomSortOrder = "PERCENT_DIFFERENCE"
)

type TopicFilterAttribute string

const (
	TopicFilterAttribute_DIRECT_QUICKSIGHT_OWNER           TopicFilterAttribute = "DIRECT_QUICKSIGHT_OWNER"
	TopicFilterAttribute_DIRECT_QUICKSIGHT_SOLE_OWNER      TopicFilterAttribute = "DIRECT_QUICKSIGHT_SOLE_OWNER"
	TopicFilterAttribute_DIRECT_QUICKSIGHT_VIEWER_OR_OWNER TopicFilterAttribute = "DIRECT_QUICKSIGHT_VIEWER_OR_OWNER"
	TopicFilterAttribute_QUICKSIGHT_OWNER                  TopicFilterAttribute = "QUICKSIGHT_OWNER"
	TopicFilterAttribute_QUICKSIGHT_USER                   TopicFilterAttribute = "QUICKSIGHT_USER"
	TopicFilterAttribute_QUICKSIGHT_VIEWER_OR_OWNER        TopicFilterAttribute = "QUICKSIGHT_VIEWER_OR_OWNER"
	TopicFilterAttribute_TOPIC_NAME                        TopicFilterAttribute = "TOPIC_NAME"
)

type TopicFilterOperator string

const (
	TopicFilterOperator_StringEquals TopicFilterOperator = "StringEquals"
	TopicFilterOperator_StringLike   TopicFilterOperator = "StringLike"
)

type TopicIRFilterFunction string

const (
	TopicIRFilterFunction_CONTAINS        TopicIRFilterFunction = "CONTAINS"
	TopicIRFilterFunction_CONTAINS_STRING TopicIRFilterFunction = "CONTAINS_STRING"
	TopicIRFilterFunction_ENDS_WITH       TopicIRFilterFunction = "ENDS_WITH"
	TopicIRFilterFunction_EXACT           TopicIRFilterFunction = "EXACT"
	TopicIRFilterFunction_LAST            TopicIRFilterFunction = "LAST"
	TopicIRFilterFunction_NEXT            TopicIRFilterFunction = "NEXT"
	TopicIRFilterFunction_NOW             TopicIRFilterFunction = "NOW"
	TopicIRFilterFunction_PREVIOUS        TopicIRFilterFunction = "PREVIOUS"
	TopicIRFilterFunction_STARTS_WITH     TopicIRFilterFunction = "STARTS_WITH"
	TopicIRFilterFunction_THIS            TopicIRFilterFunction = "THIS"
)

type TopicIRFilterType string

const (
	TopicIRFilterType_ACCEPT_ALL_FILTER       TopicIRFilterType = "ACCEPT_ALL_FILTER"
	TopicIRFilterType_CATEGORY_FILTER         TopicIRFilterType = "CATEGORY_FILTER"
	TopicIRFilterType_DATE_RANGE_FILTER       TopicIRFilterType = "DATE_RANGE_FILTER"
	TopicIRFilterType_EQUALS                  TopicIRFilterType = "EQUALS"
	TopicIRFilterType_NUMERIC_EQUALITY_FILTER TopicIRFilterType = "NUMERIC_EQUALITY_FILTER"
	TopicIRFilterType_NUMERIC_RANGE_FILTER    TopicIRFilterType = "NUMERIC_RANGE_FILTER"
	TopicIRFilterType_RANK_LIMIT_FILTER       TopicIRFilterType = "RANK_LIMIT_FILTER"
	TopicIRFilterType_RELATIVE_DATE_FILTER    TopicIRFilterType = "RELATIVE_DATE_FILTER"
	TopicIRFilterType_TOP_BOTTOM_FILTER       TopicIRFilterType = "TOP_BOTTOM_FILTER"
)

type TopicNumericSeparatorSymbol string

const (
	TopicNumericSeparatorSymbol_COMMA TopicNumericSeparatorSymbol = "COMMA"
	TopicNumericSeparatorSymbol_DOT   TopicNumericSeparatorSymbol = "DOT"
)

type TopicRefreshStatus string

const (
	TopicRefreshStatus_CANCELLED   TopicRefreshStatus = "CANCELLED"
	TopicRefreshStatus_COMPLETED   TopicRefreshStatus = "COMPLETED"
	TopicRefreshStatus_FAILED      TopicRefreshStatus = "FAILED"
	TopicRefreshStatus_INITIALIZED TopicRefreshStatus = "INITIALIZED"
	TopicRefreshStatus_RUNNING     TopicRefreshStatus = "RUNNING"
)

type TopicRelativeDateFilterFunction string

const (
	TopicRelativeDateFilterFunction_LAST     TopicRelativeDateFilterFunction = "LAST"
	TopicRelativeDateFilterFunction_NEXT     TopicRelativeDateFilterFunction = "NEXT"
	TopicRelativeDateFilterFunction_NOW      TopicRelativeDateFilterFunction = "NOW"
	TopicRelativeDateFilterFunction_PREVIOUS TopicRelativeDateFilterFunction = "PREVIOUS"
	TopicRelativeDateFilterFunction_THIS     TopicRelativeDateFilterFunction = "THIS"
)

type TopicScheduleType string

const (
	TopicScheduleType_DAILY   TopicScheduleType = "DAILY"
	TopicScheduleType_HOURLY  TopicScheduleType = "HOURLY"
	TopicScheduleType_MONTHLY TopicScheduleType = "MONTHLY"
	TopicScheduleType_WEEKLY  TopicScheduleType = "WEEKLY"
)

type TopicSortDirection string

const (
	TopicSortDirection_ASCENDING  TopicSortDirection = "ASCENDING"
	TopicSortDirection_DESCENDING TopicSortDirection = "DESCENDING"
)

type TopicTimeGranularity string

const (
	TopicTimeGranularity_DAY     TopicTimeGranularity = "DAY"
	TopicTimeGranularity_HOUR    TopicTimeGranularity = "HOUR"
	TopicTimeGranularity_MINUTE  TopicTimeGranularity = "MINUTE"
	TopicTimeGranularity_MONTH   TopicTimeGranularity = "MONTH"
	TopicTimeGranularity_QUARTER TopicTimeGranularity = "QUARTER"
	TopicTimeGranularity_SECOND  TopicTimeGranularity = "SECOND"
	TopicTimeGranularity_WEEK    TopicTimeGranularity = "WEEK"
	TopicTimeGranularity_YEAR    TopicTimeGranularity = "YEAR"
)

type TopicUserExperienceVersion string

const (
	TopicUserExperienceVersion_LEGACY                TopicUserExperienceVersion = "LEGACY"
	TopicUserExperienceVersion_NEW_READER_EXPERIENCE TopicUserExperienceVersion = "NEW_READER_EXPERIENCE"
)

type TransposedColumnType string

const (
	TransposedColumnType_ROW_HEADER_COLUMN TransposedColumnType = "ROW_HEADER_COLUMN"
	TransposedColumnType_VALUE_COLUMN      TransposedColumnType = "VALUE_COLUMN"
)

type URLTargetConfiguration string

const (
	URLTargetConfiguration_NEW_TAB    URLTargetConfiguration = "NEW_TAB"
	URLTargetConfiguration_NEW_WINDOW URLTargetConfiguration = "NEW_WINDOW"
	URLTargetConfiguration_SAME_TAB   URLTargetConfiguration = "SAME_TAB"
)

type UndefinedSpecifiedValueType string

const (
	UndefinedSpecifiedValueType_LEAST UndefinedSpecifiedValueType = "LEAST"
	UndefinedSpecifiedValueType_MOST  UndefinedSpecifiedValueType = "MOST"
)

type UserRole string

const (
	UserRole_ADMIN             UserRole = "ADMIN"
	UserRole_ADMIN_PRO         UserRole = "ADMIN_PRO"
	UserRole_AUTHOR            UserRole = "AUTHOR"
	UserRole_AUTHOR_PRO        UserRole = "AUTHOR_PRO"
	UserRole_READER            UserRole = "READER"
	UserRole_READER_PRO        UserRole = "READER_PRO"
	UserRole_RESTRICTED_AUTHOR UserRole = "RESTRICTED_AUTHOR"
	UserRole_RESTRICTED_READER UserRole = "RESTRICTED_READER"
)

type VPCConnectionAvailabilityStatus string

const (
	VPCConnectionAvailabilityStatus_AVAILABLE           VPCConnectionAvailabilityStatus = "AVAILABLE"
	VPCConnectionAvailabilityStatus_PARTIALLY_AVAILABLE VPCConnectionAvailabilityStatus = "PARTIALLY_AVAILABLE"
	VPCConnectionAvailabilityStatus_UNAVAILABLE         VPCConnectionAvailabilityStatus = "UNAVAILABLE"
)

type VPCConnectionResourceStatus string

const (
	VPCConnectionResourceStatus_CREATION_FAILED      VPCConnectionResourceStatus = "CREATION_FAILED"
	VPCConnectionResourceStatus_CREATION_IN_PROGRESS VPCConnectionResourceStatus = "CREATION_IN_PROGRESS"
	VPCConnectionResourceStatus_CREATION_SUCCESSFUL  VPCConnectionResourceStatus = "CREATION_SUCCESSFUL"
	VPCConnectionResourceStatus_DELETED              VPCConnectionResourceStatus = "DELETED"
	VPCConnectionResourceStatus_DELETION_FAILED      VPCConnectionResourceStatus = "DELETION_FAILED"
	VPCConnectionResourceStatus_DELETION_IN_PROGRESS VPCConnectionResourceStatus = "DELETION_IN_PROGRESS"
	VPCConnectionResourceStatus_UPDATE_FAILED        VPCConnectionResourceStatus = "UPDATE_FAILED"
	VPCConnectionResourceStatus_UPDATE_IN_PROGRESS   VPCConnectionResourceStatus = "UPDATE_IN_PROGRESS"
	VPCConnectionResourceStatus_UPDATE_SUCCESSFUL    VPCConnectionResourceStatus = "UPDATE_SUCCESSFUL"
)

type ValidationStrategyMode string

const (
	ValidationStrategyMode_LENIENT ValidationStrategyMode = "LENIENT"
	ValidationStrategyMode_STRICT  ValidationStrategyMode = "STRICT"
)

type ValueWhenUnsetOption string

const (
	ValueWhenUnsetOption_NULL              ValueWhenUnsetOption = "NULL"
	ValueWhenUnsetOption_RECOMMENDED_VALUE ValueWhenUnsetOption = "RECOMMENDED_VALUE"
)

type VerticalTextAlignment string

const (
	VerticalTextAlignment_AUTO   VerticalTextAlignment = "AUTO"
	VerticalTextAlignment_BOTTOM VerticalTextAlignment = "BOTTOM"
	VerticalTextAlignment_MIDDLE VerticalTextAlignment = "MIDDLE"
	VerticalTextAlignment_TOP    VerticalTextAlignment = "TOP"
)

type Visibility string

const (
	Visibility_HIDDEN  Visibility = "HIDDEN"
	Visibility_VISIBLE Visibility = "VISIBLE"
)

type VisualCustomActionTrigger string

const (
	VisualCustomActionTrigger_DATA_POINT_CLICK VisualCustomActionTrigger = "DATA_POINT_CLICK"
	VisualCustomActionTrigger_DATA_POINT_MENU  VisualCustomActionTrigger = "DATA_POINT_MENU"
)

type VisualHighlightTrigger string

const (
	VisualHighlightTrigger_DATA_POINT_CLICK VisualHighlightTrigger = "DATA_POINT_CLICK"
	VisualHighlightTrigger_DATA_POINT_HOVER VisualHighlightTrigger = "DATA_POINT_HOVER"
	VisualHighlightTrigger_NONE             VisualHighlightTrigger = "NONE"
)

type VisualRole string

const (
	VisualRole_COMPLIMENTARY VisualRole = "COMPLIMENTARY"
	VisualRole_FALLBACK      VisualRole = "FALLBACK"
	VisualRole_FRAGMENT      VisualRole = "FRAGMENT"
	VisualRole_MULTI_INTENT  VisualRole = "MULTI_INTENT"
	VisualRole_PRIMARY       VisualRole = "PRIMARY"
)

type WebCrawlerAuthType string

const (
	WebCrawlerAuthType_BASIC_AUTH WebCrawlerAuthType = "BASIC_AUTH"
	WebCrawlerAuthType_FORM       WebCrawlerAuthType = "FORM"
	WebCrawlerAuthType_NO_AUTH    WebCrawlerAuthType = "NO_AUTH"
	WebCrawlerAuthType_SAML       WebCrawlerAuthType = "SAML"
)

type WidgetStatus string

const (
	WidgetStatus_DISABLED WidgetStatus = "DISABLED"
	WidgetStatus_ENABLED  WidgetStatus = "ENABLED"
)

type WordCloudCloudLayout string

const (
	WordCloudCloudLayout_FLUID  WordCloudCloudLayout = "FLUID"
	WordCloudCloudLayout_NORMAL WordCloudCloudLayout = "NORMAL"
)

type WordCloudWordCasing string

const (
	WordCloudWordCasing_EXISTING_CASE WordCloudWordCasing = "EXISTING_CASE"
	WordCloudWordCasing_LOWER_CASE    WordCloudWordCasing = "LOWER_CASE"
)

type WordCloudWordOrientation string

const (
	WordCloudWordOrientation_HORIZONTAL              WordCloudWordOrientation = "HORIZONTAL"
	WordCloudWordOrientation_HORIZONTAL_AND_VERTICAL WordCloudWordOrientation = "HORIZONTAL_AND_VERTICAL"
)

type WordCloudWordPadding string

const (
	WordCloudWordPadding_LARGE  WordCloudWordPadding = "LARGE"
	WordCloudWordPadding_MEDIUM WordCloudWordPadding = "MEDIUM"
	WordCloudWordPadding_NONE   WordCloudWordPadding = "NONE"
	WordCloudWordPadding_SMALL  WordCloudWordPadding = "SMALL"
)

type WordCloudWordScaling string

const (
	WordCloudWordScaling_EMPHASIZE WordCloudWordScaling = "EMPHASIZE"
	WordCloudWordScaling_NORMAL    WordCloudWordScaling = "NORMAL"
)
